import type { Catalog } from "../../types/catalog";

export const fixtureCatalog: Catalog = {
  schema_version: 1,
  api_base_path: "/api/external/v1",
  generated_at: "2026-01-01T00:00:00Z",
  endpoint_count: 7,
  query_count: 2,
  mutation_count: 5,
  types: {
    primitives: {
      id: { encoded_type: "string" },
    },
    objects: {
      contextual_date: {
        fields: [
          {
            name: "date_type",
            type: { kind: "named", name: "contextual_date_type" },
            optional: false,
            nullable: false,
            has_default: false,
            default: null,
          },
          {
            name: "value",
            type: { kind: "named", name: "string" },
            optional: false,
            nullable: false,
            has_default: false,
            default: null,
          },
          {
            name: "date",
            type: { kind: "named", name: "date" },
            optional: false,
            nullable: false,
            has_default: false,
            default: null,
          },
        ],
      },
      task_status: {
        fields: [
          {
            name: "id",
            type: { kind: "named", name: "string" },
            optional: false,
            nullable: false,
            has_default: false,
            default: null,
          },
          {
            name: "label",
            type: { kind: "named", name: "string" },
            optional: false,
            nullable: false,
            has_default: false,
            default: null,
          },
        ],
      },
    },
    enums: {
      contextual_date_type: ["day", "month", "quarter", "year"],
      task_type: ["project", "space"],
    },
    int_enums: {},
    unions: {},
  },
  endpoints: [
    {
      full_name: "edit_project_name",
      namespace: null,
      name: "edit_project_name",
      type: "mutation",
      method: "POST",
      path: "/api/external/v1/edit_project_name",
      handler: "OperatelyWeb.Api.Mutations.EditProjectName",
      inputs: [
        {
          name: "project_id",
          type: { kind: "named", name: "id" },
          optional: false,
          nullable: false,
          has_default: false,
          default: null,
        },
        {
          name: "name",
          type: { kind: "named", name: "string" },
          optional: false,
          nullable: false,
          has_default: false,
          default: null,
        },
      ],
      outputs: [],
      docstring: null,
    },
    {
      full_name: "goals/update_due_date",
      namespace: "goals",
      name: "update_due_date",
      type: "mutation",
      method: "POST",
      path: "/api/external/v1/goals/update_due_date",
      handler: "OperatelyWeb.Api.Goals.UpdateDueDate",
      inputs: [
        {
          name: "goal_id",
          type: { kind: "named", name: "id" },
          optional: false,
          nullable: false,
          has_default: false,
          default: null,
        },
        {
          name: "due_date",
          type: { kind: "named", name: "contextual_date" },
          optional: false,
          nullable: true,
          has_default: false,
          default: null,
        },
      ],
      outputs: [],
      docstring: null,
    },
    {
      full_name: "goals/update_target_value",
      namespace: "goals",
      name: "update_target_value",
      type: "mutation",
      method: "POST",
      path: "/api/external/v1/goals/update_target_value",
      handler: "OperatelyWeb.Api.Goals.UpdateTargetValue",
      inputs: [
        {
          name: "goal_id",
          type: { kind: "named", name: "id" },
          optional: false,
          nullable: false,
          has_default: false,
          default: null,
        },
        {
          name: "target_value",
          type: { kind: "named", name: "float" },
          optional: false,
          nullable: false,
          has_default: false,
          default: null,
        },
        {
          name: "send_notifications",
          type: { kind: "named", name: "boolean" },
          optional: true,
          nullable: false,
          has_default: false,
          default: null,
        },
        {
          name: "subscriber_ids",
          type: {
            kind: "list",
            item: { kind: "named", name: "id" },
          },
          optional: true,
          nullable: true,
          has_default: false,
          default: null,
        },
        {
          name: "task_statuses",
          type: {
            kind: "list",
            item: { kind: "named", name: "task_status" },
          },
          optional: true,
          nullable: true,
          has_default: false,
          default: null,
        },
      ],
      outputs: [],
      docstring: null,
    },
    {
      full_name: "people/get_me",
      namespace: "people",
      name: "get_me",
      type: "query",
      method: "GET",
      path: "/api/external/v1/people/get_me",
      handler: "OperatelyWeb.Api.People.GetMe",
      inputs: [],
      outputs: [],
      docstring: "Retrieves the authenticated user.",
    },
    {
      full_name: "projects/update_description",
      namespace: "projects",
      name: "update_description",
      type: "mutation",
      method: "POST",
      path: "/api/external/v1/projects/update_description",
      handler: "OperatelyWeb.Api.Projects.UpdateDescription",
      inputs: [
        {
          name: "project_id",
          type: { kind: "named", name: "id" },
          optional: false,
          nullable: false,
          has_default: false,
          default: null,
        },
        {
          name: "description",
          type: { kind: "named", name: "json" },
          optional: false,
          nullable: false,
          has_default: false,
          default: null,
        },
      ],
      outputs: [],
      docstring: "Updates the description of a project.",
    },
    {
      full_name: "projects/get",
      namespace: "projects",
      name: "get",
      type: "query",
      method: "GET",
      path: "/api/external/v1/projects/get",
      handler: "OperatelyWeb.Api.Projects.Get",
      inputs: [
        {
          name: "id",
          type: { kind: "named", name: "id" },
          optional: false,
          nullable: false,
          has_default: false,
          default: null,
        },
        {
          name: "include_milestones",
          type: { kind: "named", name: "boolean" },
          optional: true,
          nullable: true,
          has_default: false,
          default: null,
        },
        {
          name: "include_contributors",
          type: { kind: "named", name: "boolean" },
          optional: true,
          nullable: true,
          has_default: false,
          default: null,
        },
        {
          name: "include_markdown",
          type: { kind: "named", name: "boolean" },
          optional: true,
          nullable: false,
          has_default: false,
          default: null,
        },
        {
          name: "preview",
          type: { kind: "named", name: "boolean" },
          optional: true,
          nullable: false,
          has_default: false,
          default: null,
        },
      ],
      outputs: [],
      docstring: "Retrieves a project by ID with optional includes for related data.",
    },
    {
      full_name: "tasks/update_assignee",
      namespace: "tasks",
      name: "update_assignee",
      type: "mutation",
      method: "POST",
      path: "/api/external/v1/tasks/update_assignee",
      handler: "OperatelyWeb.Api.Tasks.UpdateAssignee",
      inputs: [
        {
          name: "task_id",
          type: { kind: "named", name: "id" },
          optional: false,
          nullable: false,
          has_default: false,
          default: null,
        },
        {
          name: "assignee_id",
          type: { kind: "named", name: "id" },
          optional: true,
          nullable: true,
          has_default: false,
          default: null,
        },
        {
          name: "assignee_ids",
          type: {
            kind: "list",
            item: { kind: "named", name: "id" },
          },
          optional: true,
          nullable: true,
          has_default: false,
          default: null,
        },
        {
          name: "type",
          type: { kind: "named", name: "task_type" },
          optional: false,
          nullable: false,
          has_default: false,
          default: null,
        },
      ],
      outputs: [],
      docstring: "Updates the assignees of a task.",
    },
  ],
};
