//
// Automatically generated with mix operate.gen.feed.items.index
// Do not edit this file manually
//

import * as React from "react";

export default function FeedItem({ activity }) {
  const activityType = activity.content.__typename;

  switch (activityType) {
    default:
      throw "unhandled activity type " + activityType + " in assets/js/components/Feed/FeedItem/index.tsx";
  }
}
