import WorkMap from "../components";
import { TimeframeSelector } from "../../TimeframeSelector";
import { PrivacyIndicator } from "../../PrivacyIndicator";
import { currentMonth, currentQuarter, currentYear } from "../../utils/timeframes";

function genAvatar(id: string) {
  return `https://images.unsplash.com/${id}?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80`;
}

const people = {
  alex: {
    id: "user-alex",
    fullName: "Alex R.",
    avatarUrl: genAvatar("photo-1500648767791-00dcc994a43e"),
  },
  sophia: {
    id: "user-sophia",
    fullName: "Sophia T.",
    avatarUrl: genAvatar("photo-1438761681033-6461ffad8d80"),
  },
  jennifer: {
    id: "user-jennifer",
    fullName: "Jennifer L.",
    avatarUrl: genAvatar("photo-1494790108377-be9c29b29330"),
  },
  maximiliano: {
    id: "user-maximiliano",
    fullName: "Maximiliano Alessandro Hernández-Rodríguez",
    avatarUrl: genAvatar("photo-1507003211169-0a1dd7228f2d"),
  },
};

function getTimeframe(timeframe: TimeframeSelector.Timeframe) {
  return {
    ...timeframe,
    startDate: timeframe.startDate?.toISOString(),
    endDate: timeframe.endDate?.toISOString(),
  };
}

export const mockSingleItem: WorkMap.Item = {
  id: "goal-standalone",
  parentId: null,
  type: "goal",
  name: "Single standalone goal with no children",
  status: "on_track",
  progress: 50,
  space: { id: "space-general", name: "General" },
  spacePath: "#",
  owner: people.alex,
  ownerPath: "#",
  itemPath: "#",
  isNew: false,
  completedOn: null,
  nextStep: "Working on this standalone goal",
  privacy: "internal" as PrivacyIndicator.PrivacyLevels,
  timeframe: getTimeframe(currentQuarter()),
  children: [],
};

export const mockItems: WorkMap.Item[] = [
  {
    id: "goal-1",
    parentId: null,
    type: "goal",
    name: "Acquire the first users of Operately outside Semaphore",
    status: "on_track",
    progress: 45,
    space: { id: "space-general", name: "General" },
    spacePath: "#",
    owner: people.maximiliano,
    ownerPath: "#",
    itemPath: "#",
    isNew: false,
    completedOn: null,
    nextStep: "People are signing up for SaaS",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: getTimeframe(currentYear()),
    children: [
      {
        id: "project-1",
        parentId: "goal-1",
        type: "project",
        name: "Document features in Help Center",
        status: "completed",
        progress: 100,
        space: { id: "space-product", name: "Product" },
        spacePath: "#",
        owner: people.sophia,
        ownerPath: "#",
        itemPath: "#",
        isNew: false,
        completedOn: "2025-03-10T00:00:00.000Z",
        nextStep: "",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: {
          startDate: "2024-01-15T00:00:00.000Z",
          endDate: "2025-03-31T00:00:00.000Z",
          type: "days",
        },
        children: [],
      },
      {
        id: "project-2",
        parentId: "goal-1",
        type: "project",
        name: "Release 0.4",
        status: "paused",
        progress: 30,
        space: { id: "space-product", name: "Product" },
        spacePath: "#",
        owner: null,
        ownerPath: "#",
        itemPath: "#",
        isNew: false,
        completedOn: null,
        nextStep: "All weekly updates are collected",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: {
          startDate: "2024-01-01T00:00:00.000Z",
          endDate: "2025-02-07T00:00:00.000Z",
          type: "days",
        },
        children: [],
      },
      {
        id: "goal-1-1",
        parentId: "goal-1",
        type: "goal",
        name: "Increase user engagement by 50%",
        status: "on_track",
        progress: 60,
        space: { name: "Marketing", id: "space-marketing" },
        spacePath: "#",
        owner: people.sophia,
        ownerPath: "#",
        itemPath: "#",
        isNew: false,
        completedOn: null,
        nextStep: "Launch email campaign",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: getTimeframe(currentYear()),
        children: [
          {
            id: "project-3",
            parentId: "goal-1-1",
            type: "project",
            name: "Create onboarding email sequence",
            status: "paused",
            progress: 75,
            space: { name: "Marketing", id: "space-marketing" },
            spacePath: "#",
            owner: people.jennifer,
            ownerPath: "#",
            itemPath: "#",
            isNew: false,
            completedOn: null,
            nextStep: "Finalize email templates",
            privacy: "internal" as PrivacyIndicator.PrivacyLevels,
            timeframe: {
              startDate: "2024-06-15T00:00:00.000Z",
              endDate: "2024-10-01T00:00:00.000Z",
              type: "days",
            },
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: "goal-2",
    parentId: null,
    type: "goal",
    name: "Improve customer onboarding experience",
    status: "caution",
    progress: 25,
    space: { id: "space-rd", name: "R&D" },
    spacePath: "#",
    owner: people.jennifer,
    ownerPath: "#",
    itemPath: "#",
    isNew: false,
    completedOn: null,
    nextStep: "Conduct user interviews",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: getTimeframe(currentQuarter()),
    children: [
      {
        id: "goal-2-1",
        parentId: "goal-2",
        type: "goal",
        name: "Reduce onboarding time by 30%",
        status: "off_track",
        progress: 15,
        space: { id: "space-cs", name: "Customer Success" },
        spacePath: "#",
        owner: null,
        ownerPath: "#",
        itemPath: "#",
        isNew: false,
        completedOn: null,
        nextStep: "Identify bottlenecks in process",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: getTimeframe(currentQuarter()),
        children: [
          {
            id: "goal-2-1-1",
            parentId: "goal-2-1",
            type: "goal",
            name: "Automate user account setup",
            status: "on_track",
            progress: 40,
            space: { id: "space-eng", name: "Engineering" },
            spacePath: "#",
            owner: people.sophia,
            ownerPath: "#",
            itemPath: "#",
            isNew: false,
            completedOn: null,
            nextStep: "Complete backend integration",
            timeframe: getTimeframe(currentQuarter()),
            privacy: "secret" as PrivacyIndicator.PrivacyLevels,
            children: [
              {
                id: "project-8",
                parentId: "goal-2-1-1",
                type: "project",
                name: "Implement secure authentication service",
                status: "on_track",
                progress: 35,
                space: { id: "space-eng", name: "Engineering" },
                spacePath: "#",
                owner: people.alex,
                ownerPath: "#",
                itemPath: "#",
                isNew: false,
                completedOn: null,
                nextStep: "Complete OAuth2 integration",
                privacy: "secret" as PrivacyIndicator.PrivacyLevels,
                timeframe: {
                  startDate: "2025-04-15T00:00:00.000Z",
                  endDate: "2025-07-30T00:00:00.000Z",
                  type: "days",
                },
                children: [],
              },
            ],
          },
          {
            id: "project-6",
            parentId: "goal-2-1",
            type: "project",
            name: "Implement self-guided tutorial",
            status: "on_track",
            progress: 25,
            space: { id: "space-cs", name: "Customer Success" },
            spacePath: "#",
            owner: people.jennifer,
            ownerPath: "#",
            itemPath: "#",
            isNew: false,
            completedOn: null,
            nextStep: "Finalize content outline",
            timeframe: {
              startDate: "2024-03-01T00:00:00.000Z",
              endDate: "2025-04-30T00:00:00.000Z",
              type: "days",
            },
            privacy: "confidential" as PrivacyIndicator.PrivacyLevels,
            children: [],
          },
        ],
      },
      {
        id: "project-4",
        parentId: "goal-2",
        type: "project",
        name: "Redesign welcome screen",
        status: "on_track",
        progress: 40,
        space: { id: "space-product", name: "Product" },
        spacePath: "#",
        owner: people.alex,
        ownerPath: "#",
        itemPath: "#",
        isNew: false,
        completedOn: null,
        nextStep: "Finalize mockups",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: {
          startDate: "2025-02-01T00:00:00.000Z",
          endDate: "2025-04-20T00:00:00.000Z",
          type: "days",
        },
        children: [],
      },
    ],
  },
  {
    id: "goal-3",
    parentId: null,
    type: "goal",
    name: "Expand to international markets",
    status: "on_track",
    progress: 35,
    space: { id: "space-sales", name: "Sales" },
    spacePath: "#",
    owner: people.alex,
    ownerPath: "#",
    itemPath: "#",
    isNew: false,
    completedOn: null,
    nextStep: "Complete market research",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: getTimeframe(currentYear()),
    children: [
      {
        id: "goal-3-1",
        parentId: "goal-3",
        type: "goal",
        name: "Launch in European market",
        status: "on_track",
        progress: 50,
        space: { id: "space-intl", name: "International" },
        spacePath: "#",
        owner: people.jennifer,
        ownerPath: "#",
        itemPath: "#",
        isNew: false,
        completedOn: null,
        nextStep: "Establish legal entity",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: getTimeframe(currentYear()),
        children: [
          {
            id: "project-5",
            parentId: "goal-3-1",
            type: "project",
            name: "GDPR compliance implementation",
            status: "caution",
            progress: 30,
            space: { id: "space-legal", name: "Legal" },
            spacePath: "#",
            owner: people.sophia,
            ownerPath: "#",
            itemPath: "#",
            isNew: false,
            completedOn: null,
            nextStep: "Complete data audit",
            privacy: "internal" as PrivacyIndicator.PrivacyLevels,
            timeframe: {
              startDate: "2025-04-01T00:00:00.000Z",
              endDate: "2025-08-01T00:00:00.000Z",
              type: "days",
            },
            children: [],
          },
        ],
      },
      {
        id: "goal-3-2",
        parentId: "goal-3",
        type: "goal",
        name: "Establish comprehensive strategic partnerships with key industry leaders across multiple sectors to drive sustainable long-term growth and market penetration",
        status: "on_track",
        progress: 25,
        space: { name: "Business Development", id: "space-bd" },
        owner: people.alex,
        isNew: false,
        completedOn: null,
        nextStep: "Identify potential partners",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: getTimeframe(currentYear()),
        ownerPath: "#",
        spacePath: "#",
        itemPath: "#",
        children: [],
      },
    ],
  },
  {
    id: "goal-4",
    parentId: null,
    type: "goal",
    name: "Legacy system migration to cloud infrastructure",
    status: "completed",
    progress: 100,
    space: { id: "space-eng", name: "Engineering" },
    spacePath: "#",
    owner: people.alex,
    ownerPath: "#",
    itemPath: "#",
    isNew: false,
    completedOn: "2023-12-15T00:00:00.000Z",
    nextStep: "",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: {
      startDate: "2023-02-01T00:00:00.000Z",
      endDate: "2023-12-31T00:00:00.000Z",
      type: "days",
    },
    children: [
      {
        id: "project-4-1",
        parentId: "goal-4",
        type: "project",
        name: "Legacy database migration",
        status: "completed",
        progress: 100,
        space: { id: "space-eng", name: "Engineering" },
        spacePath: "#",
        owner: people.sophia,
        ownerPath: "#",
        itemPath: "#",
        isNew: false,
        completedOn: "2024-06-15T00:00:00.000Z",
        nextStep: "",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: {
          startDate: "2024-03-01T00:00:00.000Z",
          type: "days",
        },
        children: [],
      },
    ],
  },
  {
    id: "goal-5",
    parentId: null,
    type: "goal",
    name: "Develop sustainable AI-powered analytics platform",
    status: "on_track",
    progress: 15,
    space: { id: "space-rd", name: "R&D" },
    spacePath: "#",
    owner: people.sophia,
    ownerPath: "#",
    itemPath: "#",
    isNew: false,
    completedOn: null,
    nextStep: "Complete initial research phase",
    privacy: "confidential" as PrivacyIndicator.PrivacyLevels,
    timeframe: {
      startDate: "2024-03-01T00:00:00.000Z",
      endDate: "2028-12-31T00:00:00.000Z",
      type: "days",
    },
    children: [
      {
        id: "project-7",
        parentId: "goal-5",
        type: "project",
        name: "Research phase: ML model selection",
        status: "on_track",
        progress: 40,
        space: { id: "space-rd", name: "R&D" },
        spacePath: "#",
        owner: people.jennifer,
        ownerPath: "#",
        itemPath: "#",
        isNew: false,
        completedOn: null,
        nextStep: "Evaluate model performance metrics",
        privacy: "confidential" as PrivacyIndicator.PrivacyLevels,
        timeframe: {
          startDate: "2024-03-01T00:00:00.000Z",
          endDate: "2025-06-30T00:00:00.000Z",
          type: "days",
        },
        children: [],
      },
    ],
  },
];

export const onlyGoals: WorkMap.Item[] = [
  {
    id: "goal-g1",
    parentId: null,
    type: "goal",
    name: "Increase NPS score",
    status: "caution",
    progress: 60,
    space: { id: "space-cs", name: "Customer Success" },
    spacePath: "#",
    owner: people.alex,
    ownerPath: "#",
    itemPath: "#",
    isNew: false,
    completedOn: null,
    nextStep: "Send Q3 survey",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: getTimeframe(currentQuarter()),
    children: [
      {
        id: "goal-g1-1",
        parentId: "goal-g1",
        type: "goal",
        name: "Launch new CSAT tool",
        status: "achieved",
        progress: 80,
        space: { id: "space-cs", name: "Customer Success" },
        spacePath: "#",
        owner: people.sophia,
        ownerPath: "#",
        itemPath: "#",
        isNew: false,
        completedOn: "2025-08-15T00:00:00.000Z",
        nextStep: "Enable feedback widget",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: getTimeframe(currentMonth()),
        children: [],
      },
      {
        id: "goal-g1-2",
        parentId: "goal-g1",
        type: "goal",
        name: "Reduce churn by 10%",
        status: "missed",
        progress: 50,
        space: { id: "space-cs", name: "Customer Success" },
        spacePath: "#",
        owner: people.jennifer,
        ownerPath: "#",
        itemPath: "#",
        isNew: false,
        completedOn: null,
        nextStep: "Analyze churn data",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: getTimeframe(currentQuarter()),
        children: [],
      },
    ],
  },
  {
    id: "goal-g2",
    parentId: null,
    type: "goal",
    name: "Expand to APAC region",
    status: "missed",
    progress: 30,
    space: { id: "space-growth", name: "Growth" },
    spacePath: "#",
    owner: people.sophia,
    ownerPath: "#",
    itemPath: "#",
    isNew: false,
    completedOn: null,
    nextStep: "Research local partners",
    privacy: "secret" as PrivacyIndicator.PrivacyLevels,
    timeframe: getTimeframe(currentYear()),
    children: [
      {
        id: "goal-g2-1",
        parentId: "goal-g2",
        type: "goal",
        name: "Localize product",
        status: "pending",
        progress: 40,
        space: { id: "space-growth", name: "Growth" },
        spacePath: "#",
        owner: people.alex,
        ownerPath: "#",
        itemPath: "#",
        isNew: false,
        completedOn: null,
        nextStep: "Hire translators",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: getTimeframe(currentQuarter()),
        children: [],
      },
      {
        id: "goal-g2-2",
        parentId: "goal-g2",
        type: "goal",
        name: "APAC marketing campaign",
        status: "achieved",
        progress: 25,
        space: { id: "space-growth", name: "Growth" },
        spacePath: "#",
        owner: people.jennifer,
        ownerPath: "#",
        itemPath: "#",
        isNew: false,
        completedOn: null,
        nextStep: "Draft campaign assets",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: getTimeframe(currentQuarter()),
        children: [],
      },
    ],
  },
];

export const onlyProjects: WorkMap.Item[] = [
  {
    id: "project-1",
    parentId: null,
    type: "project",
    name: "Mobile app v2",
    status: "missed",
    progress: 70,
    space: { id: "space-mobile", name: "Mobile" },
    spacePath: "#",
    owner: people.sophia,
    ownerPath: "#",
    itemPath: "#",
    isNew: false,
    completedOn: null,
    nextStep: "Start beta testing",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: {
      startDate: "2025-01-10T00:00:00.000Z",
      endDate: "2025-09-30T00:00:00.000Z",
      type: "days",
    },
    children: [],
  },
  {
    id: "project-2",
    parentId: null,
    type: "project",
    name: "API refactor",
    status: "paused",
    progress: 40,
    space: { id: "space-backend", name: "Backend" },
    spacePath: "#",
    owner: people.alex,
    ownerPath: "#",
    itemPath: "#",
    isNew: false,
    completedOn: null,
    nextStep: "Migrate endpoints",
    privacy: "confidential" as PrivacyIndicator.PrivacyLevels,
    timeframe: {
      startDate: "2025-02-15T00:00:00.000Z",
      endDate: "2025-10-31T00:00:00.000Z",
      type: "days",
    },
    children: [],
  },
  {
    id: "project-3",
    parentId: null,
    type: "project",
    name: "Website redesign",
    status: "achieved",
    progress: 50,
    space: { id: "space-design", name: "Design" },
    spacePath: "#",
    owner: people.jennifer,
    ownerPath: "#",
    itemPath: "#",
    isNew: false,
    completedOn: "2025-07-31T00:00:00.000Z",
    nextStep: "Finalize homepage",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: {
      startDate: "2025-03-01T00:00:00.000Z",
      endDate: "2025-07-31T00:00:00.000Z",
      type: "days",
    },
    children: [],
  },
];

export const onlyCompleted: WorkMap.Item[] = [
  {
    id: "goal-10",
    parentId: null,
    type: "goal",
    name: "Achieve Series B funding",
    status: "completed",
    progress: 100,
    space: { id: "space-finance", name: "Finance" },
    spacePath: "#",
    owner: people.alex,
    ownerPath: "#",
    itemPath: "#",
    isNew: false,
    completedOn: "2025-06-01T00:00:00.000Z",
    nextStep: "",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: getTimeframe(currentYear()),
    children: [],
  },
  {
    id: "goal-11",
    parentId: null,
    type: "goal",
    name: "Hit 100k MAU",
    status: "completed",
    progress: 100,
    space: { id: "space-growth", name: "Growth" },
    spacePath: "#",
    isNew: false,
    completedOn: "2025-05-15T00:00:00.000Z",
    owner: people.sophia,
    ownerPath: "#",
    itemPath: "#",
    nextStep: "",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: getTimeframe(currentQuarter()),
    children: [],
  },
  {
    id: "project-10",
    parentId: null,
    type: "project",
    name: "Migrate to Vite",
    status: "completed",
    progress: 100,
    space: { id: "space-eng", name: "Engineering" },
    spacePath: "#",
    owner: people.jennifer,
    ownerPath: "#",
    itemPath: "#",
    isNew: false,
    completedOn: "2025-04-01T00:00:00.000Z",
    nextStep: "",
    privacy: "secret" as PrivacyIndicator.PrivacyLevels,
    timeframe: {
      startDate: "2025-01-15T00:00:00.000Z",
      endDate: "2025-04-01T00:00:00.000Z",
      type: "days",
    },
    children: [],
  },
];

export const createMockItem = (
  id: string,
  name: string,
  type: "goal" | "project",
  status: WorkMap.Item["status"],
  progress: number,
  hasChildren: boolean = false,
): WorkMap.Item => {
  const childItem: WorkMap.Item = {
    id: `${id}-child-1`,
    name: "Child item 1",
    parentId: id,
    type: "project",
    status: "on_track",
    progress: 50,
    space: { name: "Product", id: "space-1" },
    spacePath: "#",
    owner: people.jennifer,
    ownerPath: "#",
    nextStep: "Child next step",
    isNew: false,
    completedOn: null,
    children: [],
    itemPath: "#",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: {
      startDate: "2025-01-15T00:00:00.000Z",
      endDate: "2025-06-30T00:00:00.000Z",
      type: "days",
    },
  };

  const baseItem = {
    id,
    name,
    parentId: null,
    status,
    progress,
    space: { name: "Product", id: "space-1" },
    spacePath: "#",
    owner: people.alex,
    ownerPath: "#",
    nextStep: status === "completed" || status === "achieved" ? "" : "Next action to take",
    isNew: false,
    completedOn: status === "completed" || status === "achieved" ? "2025-03-15T00:00:00.000Z" : null,
    children: hasChildren ? [childItem] : [],
    itemPath: "#",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
  };

  if (type === "goal") {
    const year = currentYear();
    return {
      ...baseItem,
      type: "goal" as const,
      timeframe: {
        ...year,
        startDate: year.startDate?.toISOString(),
        endDate: year.endDate?.toISOString(),
      },
    };
  } else {
    return {
      ...baseItem,
      type: "project" as const,
      timeframe: {
        startDate: "2025-01-01T00:00:00.000Z",
        endDate: "2025-12-31T00:00:00.000Z",
        type: "days",
      },
    };
  }
};

// Create mock items for each status
export const mockGoalOnTrack = createMockItem("goal-1", "Improve customer experience", "goal", "on_track", 45, true);
export const mockGoalCompleted = createMockItem("goal-2", "Launch new marketing campaign", "goal", "completed", 100);
export const mockGoalAchieved = createMockItem("goal-3", "Increase website traffic by 50%", "goal", "achieved", 100);
export const mockGoalPartial = createMockItem("goal-4", "Reduce support tickets by 30%", "goal", "missed", 75);
export const mockGoalMissed = createMockItem("goal-5", "Launch mobile app by Q1", "goal", "missed", 60);
export const mockGoalPaused = createMockItem("goal-6", "Expand to international markets", "goal", "paused", 20);
export const mockGoalCaution = createMockItem("goal-7", "Implement new CRM system", "goal", "caution", 35);
export const mockGoalIssue = createMockItem("goal-8", "Migrate legacy systems", "goal", "off_track", 15);
export const mockGoalOutdated = createMockItem("goal-9", "Update legacy documentation", "goal", "outdated", 30);
export const mockProjectOnTrack = createMockItem("project-1", "Redesign product dashboard", "project", "on_track", 55);
export const mockProjectCompleted = createMockItem("project-2", "Update documentation", "project", "completed", 100);
export const mockProjectOutdated = createMockItem("project-3", "Refactor authentication", "project", "outdated", 25);

export const singleSpaceWorkMap: WorkMap.Item[] = [
  {
    id: "goal-product-strategy",
    parentId: null,
    type: "goal",
    name: "Define and execute product strategy for 2025",
    status: "on_track",
    progress: 65,
    space: { id: "space-product", name: "Product" },
    spacePath: "#",
    owner: people.alex,
    ownerPath: "#",
    itemPath: "#",
    isNew: false,
    completedOn: null,
    nextStep: "Finalize Q3 roadmap",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: getTimeframe(currentYear()),
    children: [
      {
        id: "goal-user-research",
        parentId: "goal-product-strategy",
        type: "goal",
        name: "Conduct comprehensive user research",
        status: "completed",
        progress: 100,
        space: { id: "space-product", name: "Product" },
        spacePath: "#",
        owner: people.sophia,
        ownerPath: "#",
        itemPath: "#",
        isNew: false,
        completedOn: "2025-03-15T00:00:00.000Z",
        nextStep: "",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: {
          startDate: "2025-01-10T00:00:00.000Z",
          endDate: "2025-03-15T00:00:00.000Z",
          type: "days",
        },
        children: [
          {
            id: "project-user-interviews",
            parentId: "goal-user-research",
            type: "project",
            name: "Conduct user interviews with key customers",
            status: "completed",
            progress: 100,
            space: { id: "space-product", name: "Product" },
            spacePath: "#",
            owner: people.jennifer,
            ownerPath: "#",
            itemPath: "#",
            isNew: false,
            completedOn: "2025-02-20T00:00:00.000Z",
            nextStep: "",
            privacy: "internal" as PrivacyIndicator.PrivacyLevels,
            timeframe: {
              startDate: "2025-01-15T00:00:00.000Z",
              endDate: "2025-02-20T00:00:00.000Z",
              type: "days",
            },
            children: [],
          },
          {
            id: "project-survey-analysis",
            parentId: "goal-user-research",
            type: "project",
            name: "Analyze customer survey results",
            status: "completed",
            progress: 100,
            space: { id: "space-product", name: "Product" },
            spacePath: "#",
            owner: people.sophia,
            ownerPath: "#",
            itemPath: "#",
            isNew: false,
            completedOn: "2025-03-10T00:00:00.000Z",
            nextStep: "",
            privacy: "internal" as PrivacyIndicator.PrivacyLevels,
            timeframe: {
              startDate: "2025-02-15T00:00:00.000Z",
              endDate: "2025-03-10T00:00:00.000Z",
              type: "days",
            },
            children: [],
          },
        ],
      },
      {
        id: "goal-feature-development",
        parentId: "goal-product-strategy",
        type: "goal",
        name: "Develop and launch key product features",
        status: "caution",
        progress: 40,
        space: { id: "space-product", name: "Product" },
        spacePath: "#",
        owner: people.alex,
        ownerPath: "#",
        itemPath: "#",
        isNew: false,
        completedOn: null,
        nextStep: "Address performance issues in beta",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: {
          startDate: "2025-02-01T00:00:00.000Z",
          endDate: "2025-08-30T00:00:00.000Z",
          type: "days",
        },
        children: [
          {
            id: "project-ai-assistant",
            parentId: "goal-feature-development",
            type: "project",
            name: "AI Assistant Integration",
            status: "off_track",
            progress: 25,
            space: { id: "space-product", name: "Product" },
            spacePath: "#",
            owner: people.maximiliano,
            ownerPath: "#",
            itemPath: "#",
            isNew: false,
            completedOn: null,
            nextStep: "Fix critical performance bottleneck",
            privacy: "internal" as PrivacyIndicator.PrivacyLevels,
            timeframe: {
              startDate: "2025-02-15T00:00:00.000Z",
              endDate: "2025-06-30T00:00:00.000Z",
              type: "days",
            },
            children: [],
          },
          {
            id: "project-mobile-app",
            parentId: "goal-feature-development",
            type: "project",
            name: "Mobile App Redesign",
            status: "on_track",
            progress: 60,
            space: { id: "space-product", name: "Product" },
            spacePath: "#",
            owner: people.sophia,
            ownerPath: "#",
            itemPath: "#",
            isNew: false,
            completedOn: null,
            nextStep: "Complete user testing for new UI",
            privacy: "internal" as PrivacyIndicator.PrivacyLevels,
            timeframe: {
              startDate: "2025-03-01T00:00:00.000Z",
              endDate: "2025-07-15T00:00:00.000Z",
              type: "days",
            },
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: "goal-customer-success",
    parentId: null,
    type: "goal",
    name: "Improve customer success metrics by 40%",
    status: "on_track",
    progress: 55,
    space: { id: "space-product", name: "Product" },
    spacePath: "#",
    owner: people.jennifer,
    ownerPath: "#",
    itemPath: "#",
    isNew: false,
    completedOn: null,
    nextStep: "Launch new onboarding flow",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: getTimeframe(currentYear()),
    children: [
      {
        id: "project-onboarding",
        parentId: "goal-customer-success",
        type: "project",
        name: "Redesign customer onboarding process",
        status: "on_track",
        progress: 70,
        space: { id: "space-product", name: "Product" },
        spacePath: "#",
        owner: people.jennifer,
        ownerPath: "#",
        itemPath: "#",
        isNew: false,
        completedOn: null,
        nextStep: "Finalize tutorial videos",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: {
          startDate: "2025-02-01T00:00:00.000Z",
          endDate: "2025-06-15T00:00:00.000Z",
          type: "days",
        },
        children: [],
      },
      {
        id: "goal-support-response",
        parentId: "goal-customer-success",
        type: "goal",
        name: "Reduce support response time to under 2 hours",
        status: "paused",
        progress: 20,
        space: { id: "space-product", name: "Product" },
        spacePath: "#",
        owner: people.sophia,
        ownerPath: "#",
        itemPath: "#",
        isNew: false,
        completedOn: null,
        nextStep: "Waiting for new support team hires",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: {
          startDate: "2025-03-15T00:00:00.000Z",
          endDate: "2025-09-30T00:00:00.000Z",
          type: "days",
        },
        children: [],
      },
    ],
  },
  {
    id: "project-documentation",
    parentId: null,
    type: "project",
    name: "Comprehensive product documentation overhaul",
    status: "on_track",
    progress: 35,
    space: { id: "space-product", name: "Product" },
    spacePath: "#",
    owner: people.sophia,
    ownerPath: "#",
    itemPath: "#",
    isNew: false,
    completedOn: null,
    nextStep: "Complete API documentation section",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: {
      startDate: "2025-03-01T00:00:00.000Z",
      endDate: "2025-07-31T00:00:00.000Z",
      type: "days",
    },
    children: [],
  },
  {
    id: "project-infrastructure",
    parentId: null,
    type: "project",
    name: "Cloud infrastructure migration",
    status: "completed",
    progress: 100,
    space: { id: "space-product", name: "Product" },
    spacePath: "#",
    owner: people.alex,
    ownerPath: "#",
    itemPath: "#",
    isNew: false,
    completedOn: "2025-04-10T00:00:00.000Z",
    nextStep: "",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: {
      startDate: "2025-01-05T00:00:00.000Z",
      endDate: "2025-04-10T00:00:00.000Z",
      type: "days",
    },
    children: [],
  },
  {
    id: "goal-analytics",
    parentId: null,
    type: "goal",
    name: "Implement advanced analytics dashboard",
    status: "outdated",
    progress: 10,
    space: { id: "space-product", name: "Product" },
    spacePath: "#",
    owner: people.maximiliano,
    ownerPath: "#",
    itemPath: "#",
    isNew: false,
    completedOn: null,
    nextStep: "Update requirements based on new product direction",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: {
      startDate: "2025-02-01T00:00:00.000Z",
      endDate: "2025-05-30T00:00:00.000Z",
      type: "days",
    },
    children: [],
  },
];

export const closedParentWithOngoingChildren: WorkMap.Item[] = [
  {
    id: "goal-parent",
    parentId: null,
    type: "goal",
    name: "Enhance product platform architecture",
    status: "achieved",
    progress: 100,
    space: { id: "space-engineering", name: "Engineering" },
    spacePath: "#",
    owner: people.jennifer,
    ownerPath: "#",
    itemPath: "#",
    isNew: false,
    completedOn: "2025-03-10T00:00:00.000Z",
    nextStep: "Completed",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: {
      startDate: "2024-01-01T00:00:00.000Z",
      endDate: "2025-03-15T00:00:00.000Z",
      type: "days",
    },
    children: [
      {
        id: "goal-child-1",
        parentId: "goal-parent",
        type: "goal",
        name: "Implement microservices architecture",
        status: "on_track",
        progress: 65,
        space: { id: "space-engineering", name: "Engineering" },
        spacePath: "#",
        owner: people.alex,
        ownerPath: "#",
        itemPath: "#",
        isNew: false,
        completedOn: null,
        nextStep: "Finalize service boundaries",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: {
          startDate: "2024-04-01T00:00:00.000Z",
          endDate: "2025-06-30T00:00:00.000Z",
          type: "days",
        },
        children: [
          {
            id: "goal-child-1-1",
            parentId: "goal-child-1",
            type: "goal",
            name: "Implement service discovery",
            status: "missed",
            progress: 60,
            space: { id: "space-engineering", name: "Engineering" },
            spacePath: "#",
            owner: people.sophia,
            ownerPath: "#",
            itemPath: "#",
            isNew: false,
            completedOn: "2025-02-15T00:00:00.000Z",
            nextStep: "Missed deadline",
            privacy: "internal" as PrivacyIndicator.PrivacyLevels,
            timeframe: {
              startDate: "2024-11-01T00:00:00.000Z",
              endDate: "2025-02-01T00:00:00.000Z",
              type: "days",
            },
            children: [
              {
                id: "project-child-1-1-1",
                parentId: "goal-child-1-1",
                type: "project",
                name: "Implement Consul integration",
                status: "caution",
                progress: 35,
                space: { id: "space-engineering", name: "Engineering" },
                spacePath: "#",
                owner: people.alex,
                ownerPath: "#",
                itemPath: "#",
                isNew: false,
                completedOn: null,
                nextStep: "Resolve configuration issues",
                privacy: "internal" as PrivacyIndicator.PrivacyLevels,
                timeframe: {
                  startDate: "2025-01-15T00:00:00.000Z",
                  endDate: "2025-04-30T00:00:00.000Z",
                  type: "days",
                },
                children: [],
              },
            ],
          },
        ],
      },
      {
        id: "goal-child-2",
        parentId: "goal-parent",
        type: "goal",
        name: "Migrate legacy systems",
        status: "caution",
        progress: 40,
        space: { id: "space-engineering", name: "Engineering" },
        spacePath: "#",
        owner: people.sophia,
        ownerPath: "#",
        itemPath: "#",
        isNew: false,
        completedOn: null,
        nextStep: "Complete data migration plan",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: {
          startDate: "2024-05-01T00:00:00.000Z",
          endDate: "2025-07-15T00:00:00.000Z",
          type: "days",
        },
        children: [],
      },
      {
        id: "project-child-1",
        parentId: "goal-parent",
        type: "project",
        name: "Set up CI/CD pipeline",
        status: "on_track",
        progress: 80,
        space: { id: "space-devops", name: "DevOps" },
        spacePath: "#",
        owner: people.jennifer,
        ownerPath: "#",
        itemPath: "#",
        isNew: false,
        completedOn: null,
        nextStep: "Implement automated testing",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: {
          startDate: "2024-03-15T00:00:00.000Z",
          endDate: "2025-05-20T00:00:00.000Z",
          type: "days",
        },
        children: [],
      },
    ],
  },
];
