import { createContextualDate } from "../../DateField/mockData";
import { PrivacyIndicator } from "../../PrivacyIndicator";
import { currentMonth, currentQuarter, currentYear } from "../../utils/timeframes";
import WorkMap from "../components";

function genAvatar(id: string) {
  return `https://images.unsplash.com/${id}?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80`;
}

export const people = {
  alex: {
    id: "user-alex",
    fullName: "Alex R.",
    avatarUrl: genAvatar("photo-1500648767791-00dcc994a43e"),
  },
  sophia: {
    id: "user-sophia",
    fullName: "Sophia T.",
    avatarUrl: genAvatar("photo-1438761681033-6461ffad8d80"),
  },
  jennifer: {
    id: "user-jennifer",
    fullName: "Jennifer L.",
    avatarUrl: genAvatar("photo-1494790108377-be9c29b29330"),
  },
  maximiliano: {
    id: "user-maximiliano",
    fullName: "Maximiliano Alessandro Hernández-Rodríguez",
    avatarUrl: genAvatar("photo-1507003211169-0a1dd7228f2d"),
  },
};

function getTimeframe(timeframe) {
  return {
    startDate: timeframe.startDate ? createContextualDate(timeframe.startDate, "day") : null,
    endDate: timeframe.endDate ? createContextualDate(timeframe.endDate, "day") : null,
  };
}

function withDefaults(item: any): WorkMap.Item {
  return {
    project: null,
    projectPath: null,
    spacePath: "#",
    ownerPath: "#",
    reviewer: null,
    reviewerPath: null,
    itemPath: "#",
    isNew: false,
    completedOn: null,
    nextStep: "",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    ...item,
    children: (item.children || []).map(withDefaults),
  };
}

export const mockSingleItem: WorkMap.Item = withDefaults({
  id: "goal-standalone",
  parentId: null,
  type: "goal",
  name: "Single standalone goal with no children",
  status: "on_track",
  progress: 50,
  space: { id: "space-general", name: "General", link: "/spaces/general" },
  owner: people.alex,
  nextStep: "Working on this standalone goal",
  timeframe: getTimeframe(currentQuarter()),
  children: [],
});

export const mockItems: WorkMap.Item[] = [
  {
    id: "goal-1",
    parentId: null,
    type: "goal",
    name: "Acquire the first users of Operately outside Semaphore",
    status: "on_track",
    progress: 45,
    space: { id: "space-general", name: "General", link: "/spaces/general" },
    owner: people.maximiliano,
    nextStep: "People are signing up for SaaS",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: getTimeframe(currentYear()),
    children: [
      {
        id: "project-1",
        parentId: "goal-1",
        type: "project",
        name: "Document features in Help Center",
        status: "achieved",
        progress: 100,
        space: { id: "space-product", name: "Product", link: "/spaces/product" },
        owner: people.sophia,
        completedOn: "2025-03-10T00:00:00.000Z",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: {
          startDate: createContextualDate("2024-01-15T00:00:00.000Z", "day"),
          endDate: createContextualDate("2025-03-31T00:00:00.000Z", "day"),
        },
        children: [],
      },
      {
        id: "project-2",
        parentId: "goal-1",
        type: "project",
        name: "Release 0.4",
        status: "paused",
        progress: 30,
        space: { id: "space-product", name: "Product", link: "/spaces/product" },
        nextStep: "All weekly updates are collected",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: {
          startDate: createContextualDate("2024-01-01T00:00:00.000Z", "day"),
          endDate: createContextualDate("2025-02-07T00:00:00.000Z", "day"),
        },
        children: [],
      },
      {
        id: "goal-1-1",
        parentId: "goal-1",
        type: "goal",
        name: "Increase user engagement by 50%",
        status: "on_track",
        progress: 60,
        space: { name: "Marketing", id: "space-marketing", link: "/spaces/marketing" },
        owner: people.sophia,
        completedOn: null,
        nextStep: "Launch email campaign",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: getTimeframe(currentYear()),
        children: [
          {
            id: "project-3",
            parentId: "goal-1-1",
            type: "project",
            name: "Create onboarding email sequence",
            status: "paused",
            progress: 75,
            space: { name: "Marketing", id: "space-marketing", link: "/spaces/marketing" },
            owner: people.jennifer,
            nextStep: "Finalize email templates",
            privacy: "internal" as PrivacyIndicator.PrivacyLevels,
            timeframe: {
              startDate: createContextualDate("2024-06-15T00:00:00.000Z", "day"),
              endDate: createContextualDate("2024-10-01T00:00:00.000Z", "day"),
            },
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: "goal-2",
    parentId: null,
    type: "goal",
    name: "Improve customer onboarding experience",
    status: "caution",
    progress: 25,
    space: { id: "space-rd", name: "R&D", link: "/spaces/rd" },
    owner: people.jennifer,
    nextStep: "Conduct user interviews",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: getTimeframe(currentQuarter()),
    children: [
      {
        id: "goal-2-1",
        parentId: "goal-2",
        type: "goal",
        name: "Reduce onboarding time by 30%",
        status: "off_track",
        progress: 15,
        space: { id: "space-cs", name: "Customer Success", link: "/spaces/cs" },
        owner: null,
        nextStep: "Identify bottlenecks in process",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: getTimeframe(currentQuarter()),
        children: [
          {
            id: "goal-2-1-1",
            parentId: "goal-2-1",
            type: "goal",
            name: "Automate user account setup",
            status: "on_track",
            progress: 40,
            space: { id: "space-eng", name: "Engineering", link: "/spaces/eng" },
            owner: people.sophia,
            nextStep: "Complete backend integration",
            timeframe: getTimeframe(currentQuarter()),
            privacy: "secret" as PrivacyIndicator.PrivacyLevels,
            children: [
              {
                id: "project-8",
                parentId: "goal-2-1-1",
                type: "project",
                name: "Implement secure authentication service",
                status: "on_track",
                progress: 35,
                space: { id: "space-eng", name: "Engineering", link: "/spaces/eng" },
                owner: people.alex,
                nextStep: "Complete OAuth2 integration",
                privacy: "secret" as PrivacyIndicator.PrivacyLevels,
                timeframe: {
                  startDate: createContextualDate("2025-04-15T00:00:00.000Z", "day"),
                  endDate: createContextualDate("2025-07-30T00:00:00.000Z", "day"),
                },
                children: [],
              },
            ],
          },
          {
            id: "project-6",
            parentId: "goal-2-1",
            type: "project",
            name: "Implement self-guided tutorial",
            status: "on_track",
            progress: 25,
            space: { id: "space-cs", name: "Customer Success", link: "/spaces/cs" },
            owner: people.jennifer,
            nextStep: "Finalize content outline",
            timeframe: {
              startDate: createContextualDate("2024-03-01T00:00:00.000Z", "day"),
              endDate: createContextualDate("2025-04-30T00:00:00.000Z", "day"),
            },
            privacy: "confidential" as PrivacyIndicator.PrivacyLevels,
            children: [],
          },
        ],
      },
      {
        id: "project-4",
        parentId: "goal-2",
        type: "project",
        name: "Redesign welcome screen",
        status: "on_track",
        progress: 40,
        space: { id: "space-product", name: "Product", link: "/spaces/product" },
        owner: people.alex,
        nextStep: "Finalize mockups",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: {
          startDate: createContextualDate("2025-02-01T00:00:00.000Z", "day"),
          endDate: createContextualDate("2025-04-20T00:00:00.000Z", "day"),
        },
        children: [],
      },
    ],
  },
  {
    id: "goal-3",
    parentId: null,
    type: "goal",
    name: "Expand to international markets",
    status: "on_track",
    progress: 35,
    space: { id: "space-sales", name: "Sales", link: "/spaces/sales" },
    owner: people.alex,
    nextStep: "Complete market research",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: getTimeframe(currentYear()),
    children: [
      {
        id: "goal-3-1",
        parentId: "goal-3",
        type: "goal",
        name: "Launch in European market",
        status: "on_track",
        progress: 50,
        space: { id: "space-intl", name: "International", link: "/spaces/intl" },
        owner: people.jennifer,
        nextStep: "Establish legal entity",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: getTimeframe(currentYear()),
        children: [
          {
            id: "project-5",
            parentId: "goal-3-1",
            type: "project",
            name: "GDPR compliance implementation",
            status: "caution",
            progress: 30,
            space: { id: "space-legal", name: "Legal", link: "/spaces/legal" },
            owner: people.sophia,
            nextStep: "Complete data audit",
            privacy: "internal" as PrivacyIndicator.PrivacyLevels,
            timeframe: {
              startDate: createContextualDate("2025-04-01T00:00:00.000Z", "day"),
              endDate: createContextualDate("2025-08-01T00:00:00.000Z", "day"),
            },
            children: [],
          },
        ],
      },
      {
        id: "goal-3-2",
        parentId: "goal-3",
        type: "goal",
        name: "Establish comprehensive strategic partnerships with key industry leaders across multiple sectors to drive sustainable long-term growth and market penetration",
        status: "on_track",
        progress: 25,
        space: { name: "Business Development", id: "space-bd", link: "/spaces/bd" },
        owner: people.alex,
        nextStep: "Identify potential partners",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: getTimeframe(currentYear()),
        reviewer: null,
        children: [],
      },
    ],
  },
  {
    id: "goal-4",
    parentId: null,
    type: "goal",
    name: "Legacy system migration to cloud infrastructure",
    status: "achieved",
    progress: 100,
    space: { id: "space-eng", name: "Engineering", link: "/spaces/eng" },
    owner: people.alex,
    reviewer: null,
    completedOn: "2023-12-15T00:00:00.000Z",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: {
      startDate: createContextualDate("2023-02-01T00:00:00.000Z", "day"),
      endDate: createContextualDate("2023-12-31T00:00:00.000Z", "day"),
    },
    children: [
      {
        id: "project-4-1",
        parentId: "goal-4",
        type: "project",
        name: "Legacy database migration",
        status: "achieved",
        progress: 100,
        space: { id: "space-eng", name: "Engineering", link: "/spaces/eng" },
        owner: people.sophia,
        completedOn: "2024-06-15T00:00:00.000Z",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: {
          startDate: createContextualDate("2024-03-01T00:00:00.000Z", "day"),
          endDate: null,
        },
        children: [],
      },
    ],
  },
  {
    id: "goal-5",
    parentId: null,
    type: "goal",
    name: "Develop sustainable AI-powered analytics platform",
    status: "on_track",
    progress: 15,
    space: { id: "space-rd", name: "R&D", link: "/spaces/rd" },
    owner: people.sophia,
    nextStep: "Complete initial research phase",
    privacy: "confidential" as PrivacyIndicator.PrivacyLevels,
    timeframe: {
      startDate: createContextualDate("2024-03-01T00:00:00.000Z", "day"),
      endDate: createContextualDate("2028-12-31T00:00:00.000Z", "day"),
    },
    children: [
      {
        id: "project-7",
        parentId: "goal-5",
        type: "project",
        name: "Research phase: ML model selection",
        status: "on_track",
        progress: 40,
        space: { id: "space-rd", name: "R&D", link: "/spaces/rd" },
        owner: people.jennifer,
        nextStep: "Evaluate model performance metrics",
        privacy: "confidential" as PrivacyIndicator.PrivacyLevels,
        timeframe: {
          startDate: createContextualDate("2024-03-01T00:00:00.000Z", "day"),
          endDate: createContextualDate("2025-06-30T00:00:00.000Z", "day"),
        },
        children: [],
      },
    ],
  },
].map(withDefaults);

export const onlyGoals: WorkMap.Item[] = [
  {
    id: "goal-g1",
    parentId: null,
    type: "goal",
    name: "Increase NPS score",
    status: "caution",
    progress: 60,
    space: { id: "space-cs", name: "Customer Success", link: "/spaces/cs" },
    owner: people.alex,
    nextStep: "Send Q3 survey",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: getTimeframe(currentQuarter()),
    children: [
      {
        id: "goal-g1-1",
        parentId: "goal-g1",
        type: "goal",
        name: "Launch new CSAT tool",
        status: "achieved",
        progress: 80,
        space: { id: "space-cs", name: "Customer Success", link: "/spaces/cs" },
        owner: people.sophia,
        nextStep: "Enable feedback widget",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: getTimeframe(currentMonth()),
        children: [],
      },
      {
        id: "goal-g1-2",
        parentId: "goal-g1",
        type: "goal",
        name: "Reduce churn by 10%",
        status: "missed",
        progress: 50,
        space: { id: "space-cs", name: "Customer Success", link: "/spaces/cs" },
        owner: people.jennifer,
        nextStep: "Analyze churn data",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: getTimeframe(currentQuarter()),
        children: [],
      },
    ],
  },
  {
    id: "goal-g2",
    parentId: null,
    type: "goal",
    name: "Expand to APAC region",
    status: "missed",
    progress: 30,
    space: { id: "space-growth", name: "Growth", link: "/spaces/growth" },
    owner: people.sophia,
    nextStep: "Research local partners",
    privacy: "secret" as PrivacyIndicator.PrivacyLevels,
    timeframe: getTimeframe(currentYear()),
    children: [
      {
        id: "goal-g2-1",
        parentId: "goal-g2",
        type: "goal",
        name: "Localize product",
        status: "pending",
        progress: 40,
        space: { id: "space-growth", name: "Growth", link: "/spaces/growth" },
        owner: people.alex,
        nextStep: "Hire translators",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: getTimeframe(currentQuarter()),
        children: [],
      },
      {
        id: "goal-g2-2",
        parentId: "goal-g2",
        type: "goal",
        name: "APAC marketing campaign",
        status: "achieved",
        progress: 25,
        space: { id: "space-growth", name: "Growth", link: "/spaces/growth" },
        owner: people.jennifer,
        nextStep: "Draft campaign assets",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: getTimeframe(currentQuarter()),
        children: [],
      },
    ],
  },
].map(withDefaults);

export const onlyProjects: WorkMap.Item[] = [
  {
    id: "project-1",
    parentId: null,
    type: "project",
    name: "Mobile app v2",
    status: "missed",
    progress: 70,
    space: { id: "space-mobile", name: "Mobile", link: "/spaces/mobile" },
    owner: people.sophia,
    nextStep: "Start beta testing",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: {
      startDate: createContextualDate("2025-01-10T00:00:00.000Z", "day"),
      endDate: createContextualDate("2025-09-30T00:00:00.000Z", "day"),
    },
    children: [],
  },
  {
    id: "project-2",
    parentId: null,
    type: "project",
    name: "API refactor",
    status: "paused",
    progress: 40,
    space: { id: "space-backend", name: "Backend", link: "/backend" },
    owner: people.alex,
    nextStep: "Migrate endpoints",
    privacy: "confidential" as PrivacyIndicator.PrivacyLevels,
    timeframe: {
      startDate: createContextualDate("2025-02-15T00:00:00.000Z", "day"),
      endDate: createContextualDate("2025-10-31T00:00:00.000Z", "day"),
    },
    children: [],
  },
  {
    id: "project-3",
    parentId: null,
    type: "project",
    name: "Website redesign",
    status: "achieved",
    progress: 50,
    space: { id: "space-design", name: "Design", link: "/design" },
    owner: people.jennifer,
    completedOn: "2025-07-31T00:00:00.000Z",
    nextStep: "Finalize homepage",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: {
      startDate: createContextualDate("2025-03-01T00:00:00.000Z", "day"),
      endDate: createContextualDate("2025-07-31T00:00:00.000Z", "day"),
    },
    children: [],
  },
].map(withDefaults);

export const onlyCompleted: WorkMap.Item[] = [
  {
    id: "goal-10",
    parentId: null,
    type: "goal",
    name: "Achieve Series B funding",
    status: "achieved",
    progress: 100,
    space: { id: "space-finance", name: "Finance", link: "/finance" },
    owner: people.alex,
    completedOn: "2025-06-01T00:00:00.000Z",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: getTimeframe(currentYear()),
    children: [],
  },
  {
    id: "goal-11",
    parentId: null,
    type: "goal",
    name: "Hit 100k MAU",
    status: "achieved",
    progress: 100,
    space: { id: "space-growth", name: "Growth", link: "/growth" },
    owner: people.sophia,
    completedOn: "2025-05-15T00:00:00.000Z",
    nextStep: "",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: getTimeframe(currentQuarter()),
    children: [],
  },
  {
    id: "project-10",
    parentId: null,
    type: "project",
    name: "Migrate to Vite",
    status: "achieved",
    progress: 100,
    space: { id: "space-eng", name: "Engineering", link: "/spaces/eng" },
    owner: people.jennifer,
    completedOn: "2025-04-01T00:00:00.000Z",
    privacy: "secret" as PrivacyIndicator.PrivacyLevels,
    timeframe: {
      startDate: createContextualDate("2025-01-15T00:00:00.000Z", "day"),
      endDate: createContextualDate("2025-04-01T00:00:00.000Z", "day"),
    },
    children: [],
  },
].map(withDefaults);

export const createMockItem = (
  id: string,
  name: string,
  type: "goal" | "project",
  status: WorkMap.Item["status"],
  progress: number,
  hasChildren: boolean = false,
): WorkMap.Item => {
  const childItem: WorkMap.Item = withDefaults({
    id: `${id}-child-1`,
    name: "Child item 1",
    parentId: id,
    type: "project",
    status: "on_track",
    progress: 50,
    space: { name: "Product", id: "space-1", link: "/product" },
    owner: people.jennifer,
    nextStep: "Child next step",
    children: [],
    timeframe: {
      startDate: createContextualDate("2025-01-15T00:00:00.000Z", "day"),
      endDate: createContextualDate("2025-06-30T00:00:00.000Z", "day"),
    },
  });

  const baseItem = {
    id,
    name,
    parentId: null,
    status,
    progress,
    space: { name: "Product", id: "space-1", link: "/product" },
    owner: people.alex,
    nextStep: status === "achieved" ? "" : "Next action to take",
    completedOn: status === "achieved" ? "2025-03-15T00:00:00.000Z" : null,
    children: hasChildren ? [childItem] : [],
  };

  if (type === "goal") {
    const year = currentYear();
    return withDefaults({
      ...baseItem,
      type: "goal" as const,
      timeframe: {
        startDate: createContextualDate(year.startDate!, "year"),
        endDate: createContextualDate(year.endDate!, "year"),
      },
    });
  } else {
    return withDefaults({
      ...baseItem,
      type: "project" as const,
      timeframe: {
        startDate: createContextualDate("2025-01-01T00:00:00.000Z", "day"),
        endDate: createContextualDate("2025-12-31T00:00:00.000Z", "day"),
      },
    });
  }
};

// Create mock items for each status
export const mockGoalOnTrack = createMockItem("goal-1", "Improve customer experience", "goal", "on_track", 45, true);
export const mockGoalCompleted = createMockItem("goal-2", "Launch new marketing campaign", "goal", "achieved", 100);
export const mockGoalAchieved = createMockItem("goal-3", "Increase website traffic by 50%", "goal", "achieved", 100);
export const mockGoalPartial = createMockItem("goal-4", "Reduce support tickets by 30%", "goal", "missed", 75);
export const mockGoalMissed = createMockItem("goal-5", "Launch mobile app by Q1", "goal", "missed", 60);
export const mockGoalPaused = createMockItem("goal-6", "Expand to international markets", "goal", "paused", 20);
export const mockGoalCaution = createMockItem("goal-7", "Implement new CRM system", "goal", "caution", 35);
export const mockGoalIssue = createMockItem("goal-8", "Migrate legacy systems", "goal", "off_track", 15);
export const mockGoalOutdated = createMockItem("goal-9", "Update legacy documentation", "goal", "outdated", 30);
export const mockProjectOnTrack = createMockItem("project-1", "Redesign product dashboard", "project", "on_track", 55);
export const mockProjectCompleted = createMockItem("project-2", "Update documentation", "project", "achieved", 100);
export const mockProjectOutdated = createMockItem("project-3", "Refactor authentication", "project", "outdated", 25);

export const singleSpaceWorkMap: WorkMap.Item[] = [
  {
    id: "goal-product-strategy",
    parentId: null,
    type: "goal",
    name: "Define and execute product strategy for 2025",
    status: "on_track",
    progress: 65,
    space: { id: "space-product", name: "Product", link: "/spaces/product" },
    owner: people.alex,
    nextStep: "Finalize Q3 roadmap",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: getTimeframe(currentYear()),
    children: [
      {
        id: "goal-user-research",
        parentId: "goal-product-strategy",
        type: "goal",
        name: "Conduct comprehensive user research",
        status: "achieved",
        progress: 100,
        space: { id: "space-product", name: "Product", link: "/spaces/product" },
        owner: people.sophia,
        completedOn: "2025-03-15T00:00:00.000Z",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: {
          startDate: createContextualDate("2025-01-10T00:00:00.000Z", "day"),
          endDate: createContextualDate("2025-03-15T00:00:00.000Z", "day"),
        },
        children: [
          {
            id: "project-user-interviews",
            parentId: "goal-user-research",
            type: "project",
            name: "Conduct user interviews with key customers",
            status: "achieved",
            progress: 100,
            space: { id: "space-product", name: "Product", link: "/spaces/product" },
            owner: people.jennifer,
            completedOn: "2025-02-20T00:00:00.000Z",
            privacy: "internal" as PrivacyIndicator.PrivacyLevels,
            timeframe: {
              startDate: createContextualDate("2025-01-15T00:00:00.000Z", "day"),
              endDate: createContextualDate("2025-02-20T00:00:00.000Z", "day"),
            },
            children: [],
          },
          {
            id: "project-survey-analysis",
            parentId: "goal-user-research",
            type: "project",
            name: "Analyze customer survey results",
            status: "achieved",
            progress: 100,
            space: { id: "space-product", name: "Product", link: "/spaces/product" },
            owner: people.sophia,
            completedOn: "2025-03-10T00:00:00.000Z",
            privacy: "internal" as PrivacyIndicator.PrivacyLevels,
            timeframe: {
              startDate: createContextualDate("2025-02-15T00:00:00.000Z", "day"),
              endDate: createContextualDate("2025-03-10T00:00:00.000Z", "day"),
            },
            children: [],
          },
        ],
      },
      {
        id: "goal-feature-development",
        parentId: "goal-product-strategy",
        type: "goal",
        name: "Develop and launch key product features",
        status: "caution",
        progress: 40,
        space: { id: "space-product", name: "Product", link: "/spaces/product" },
        owner: people.alex,
        completedOn: null,
        nextStep: "Address performance issues in beta",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: {
          startDate: createContextualDate("2025-02-01T00:00:00.000Z", "day"),
          endDate: createContextualDate("2025-08-30T00:00:00.000Z", "day"),
        },
        children: [
          {
            id: "project-ai-assistant",
            parentId: "goal-feature-development",
            type: "project",
            name: "AI Assistant Integration",
            status: "off_track",
            progress: 25,
            space: { id: "space-product", name: "Product", link: "/spaces/product" },
            owner: people.maximiliano,
            nextStep: "Fix critical performance bottleneck",
            privacy: "internal" as PrivacyIndicator.PrivacyLevels,
            timeframe: {
              startDate: createContextualDate("2025-02-15T00:00:00.000Z", "day"),
              endDate: createContextualDate("2025-06-30T00:00:00.000Z", "day"),
            },
            children: [],
          },
          {
            id: "project-mobile-app",
            parentId: "goal-feature-development",
            type: "project",
            name: "Mobile App Redesign",
            status: "on_track",
            progress: 60,
            space: { id: "space-product", name: "Product", link: "/spaces/product" },
            owner: people.sophia,
            nextStep: "Complete user testing for new UI",
            privacy: "internal" as PrivacyIndicator.PrivacyLevels,
            timeframe: {
              startDate: createContextualDate("2025-03-01T00:00:00.000Z", "day"),
              endDate: createContextualDate("2025-07-15T00:00:00.000Z", "day"),
            },
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: "goal-customer-success",
    parentId: null,
    type: "goal",
    name: "Improve customer success metrics by 40%",
    status: "on_track",
    progress: 55,
    space: { id: "space-product", name: "Product", link: "/spaces/product" },
    owner: people.jennifer,
    nextStep: "Launch new onboarding flow",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: getTimeframe(currentYear()),
    children: [
      {
        id: "project-onboarding",
        parentId: "goal-customer-success",
        type: "project",
        name: "Redesign customer onboarding process",
        status: "on_track",
        progress: 70,
        space: { id: "space-product", name: "Product", link: "/spaces/product" },
        owner: people.jennifer,
        nextStep: "Finalize tutorial videos",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: {
          startDate: createContextualDate("2025-02-01T00:00:00.000Z", "day"),
          endDate: createContextualDate("2025-06-15T00:00:00.000Z", "day"),
        },
        children: [],
      },
      {
        id: "goal-support-response",
        parentId: "goal-customer-success",
        type: "goal",
        name: "Reduce support response time to under 2 hours",
        status: "paused",
        progress: 20,
        space: { id: "space-product", name: "Product", link: "/spaces/product" },
        owner: people.sophia,
        nextStep: "Waiting for new support team hires",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: {
          startDate: createContextualDate("2025-03-15T00:00:00.000Z", "day"),
          endDate: createContextualDate("2025-09-30T00:00:00.000Z", "day"),
        },
        children: [],
      },
    ],
  },
  {
    id: "project-documentation",
    parentId: null,
    type: "project",
    name: "Comprehensive product documentation overhaul",
    status: "on_track",
    progress: 35,
    space: { id: "space-product", name: "Product", link: "/spaces/product" },
    owner: people.sophia,
    nextStep: "Complete API documentation section",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: {
      startDate: createContextualDate("2025-03-01T00:00:00.000Z", "day"),
      endDate: createContextualDate("2025-07-31T00:00:00.000Z", "day"),
    },
    children: [],
  },
  {
    id: "project-infrastructure",
    parentId: null,
    type: "project",
    name: "Cloud infrastructure migration",
    status: "achieved",
    progress: 100,
    space: { id: "space-product", name: "Product", link: "/spaces/product" },
    owner: people.alex,
    completedOn: "2025-04-10T00:00:00.000Z",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: {
      startDate: createContextualDate("2025-01-05T00:00:00.000Z", "day"),
      endDate: createContextualDate("2025-04-10T00:00:00.000Z", "day"),
    },
    children: [],
  },
  {
    id: "goal-analytics",
    parentId: null,
    type: "goal",
    name: "Implement advanced analytics dashboard",
    status: "outdated",
    progress: 10,
    space: { id: "space-product", name: "Product", link: "/spaces/product" },
    owner: people.maximiliano,
    nextStep: "Update requirements based on new product direction",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: {
      startDate: createContextualDate("2025-02-01T00:00:00.000Z", "day"),
      endDate: createContextualDate("2025-05-30T00:00:00.000Z", "day"),
    },
    children: [],
  },
].map(withDefaults);

// Mock data with reviewers for demonstrating the Role column
export const mockItemsWithReviewers: WorkMap.Item[] = [
  {
    id: "goal-1",
    parentId: null,
    type: "goal",
    name: "Launch new product features",
    status: "on_track",
    progress: 65,
    space: { id: "space-product", name: "Product", link: "/spaces/product" },
    owner: people.alex,
    reviewer: people.jennifer,
    nextStep: "Complete feature testing",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: getTimeframe(currentQuarter()),
    children: [
      {
        id: "project-1",
        parentId: "goal-1",
        type: "project",
        name: "User authentication improvements",
        status: "on_track",
        progress: 80,
        space: { id: "space-eng", name: "Engineering", link: "/spaces/eng" },
        owner: people.sophia,
        reviewer: people.alex,
        nextStep: "Security audit",
        privacy: "internal" as PrivacyIndicator.PrivacyLevels,
        timeframe: {
          startDate: createContextualDate("2025-01-15T00:00:00.000Z", "day"),
          endDate: createContextualDate("2025-04-30T00:00:00.000Z", "day"),
        },
        children: [],
      },
    ],
  },
  {
    id: "goal-2",
    parentId: null,
    type: "goal",
    name: "Improve system performance",
    status: "caution",
    progress: 40,
    space: { id: "space-eng", name: "Engineering", link: "/spaces/eng" },
    owner: people.sophia,
    reviewer: people.maximiliano,
    nextStep: "Database optimization",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: getTimeframe(currentQuarter()),
    children: [],
  },
  {
    id: "project-standalone",
    parentId: null,
    type: "project",
    name: "Marketing campaign Q2",
    status: "on_track",
    progress: 55,
    space: { id: "space-marketing", name: "Marketing", link: "/spaces/marketing" },
    owner: people.jennifer,
    reviewer: people.sophia,
    nextStep: "Launch social media ads",
    privacy: "internal" as PrivacyIndicator.PrivacyLevels,
    timeframe: {
      startDate: createContextualDate("2025-04-01T00:00:00.000Z", "day"),
      endDate: createContextualDate("2025-06-30T00:00:00.000Z", "day"),
    },
    children: [],
  },
].map(withDefaults);

export const closedParentWithOngoingChildren: WorkMap.Item[] = [
  {
    id: "goal-parent",
    parentId: null,
    type: "goal",
    name: "Enhance product platform architecture",
    status: "achieved",
    progress: 100,
    space: { id: "space-engineering", name: "Engineering", link: "/spaces/engineering" },
    owner: people.jennifer,
    completedOn: "2025-03-10T00:00:00.000Z",
    nextStep: "Completed",
    timeframe: {
      startDate: createContextualDate("2024-01-01T00:00:00.000Z", "day"),
      endDate: createContextualDate("2025-03-15T00:00:00.000Z", "day"),
    },
    children: [
      {
        id: "goal-child-1",
        parentId: "goal-parent",
        type: "goal",
        name: "Implement microservices architecture",
        status: "on_track",
        progress: 65,
        space: { id: "space-engineering", name: "Engineering", link: "/spaces/engineering" },
        owner: people.alex,
        nextStep: "Finalize service boundaries",
        timeframe: {
          startDate: createContextualDate("2024-04-01T00:00:00.000Z", "day"),
          endDate: createContextualDate("2025-06-30T00:00:00.000Z", "day"),
        },
        children: [
          {
            id: "goal-child-1-1",
            parentId: "goal-child-1",
            type: "goal",
            name: "Implement service discovery",
            status: "missed",
            progress: 60,
            space: { id: "space-engineering", name: "Engineering", link: "/spaces/engineering" },
            owner: people.sophia,
            completedOn: "2025-02-15T00:00:00.000Z",
            nextStep: "Missed deadline",
            timeframe: {
              startDate: createContextualDate("2024-11-01T00:00:00.000Z", "day"),
              endDate: createContextualDate("2025-02-01T00:00:00.000Z", "day"),
            },
            children: [
              {
                id: "project-child-1-1-1",
                parentId: "goal-child-1-1",
                type: "project",
                name: "Implement Consul integration",
                status: "caution",
                progress: 35,
                space: { id: "space-engineering", name: "Engineering", link: "/spaces/engineering" },
                owner: people.alex,
                nextStep: "Resolve configuration issues",
                timeframe: {
                  startDate: createContextualDate("2025-01-15T00:00:00.000Z", "day"),
                  endDate: createContextualDate("2025-04-30T00:00:00.000Z", "day"),
                },
                children: [],
              },
            ],
          },
        ],
      },
      {
        id: "goal-child-2",
        parentId: "goal-parent",
        type: "goal",
        name: "Migrate legacy systems",
        status: "caution",
        progress: 40,
        space: { id: "space-engineering", name: "Engineering", link: "/spaces/engineering" },
        owner: people.sophia,
        nextStep: "Complete data migration plan",
        timeframe: {
          startDate: createContextualDate("2024-05-01T00:00:00.000Z", "day"),
          endDate: createContextualDate("2025-07-15T00:00:00.000Z", "day"),
        },
        children: [],
      },
      {
        id: "project-child-1",
        parentId: "goal-parent",
        type: "project",
        name: "Set up CI/CD pipeline",
        status: "on_track",
        progress: 80,
        space: { id: "space-devops", name: "DevOps", link: "/spaces/devops" },
        owner: people.jennifer,
        nextStep: "Implement automated testing",
        timeframe: {
          startDate: createContextualDate("2024-03-15T00:00:00.000Z", "day"),
          endDate: createContextualDate("2025-05-20T00:00:00.000Z", "day"),
        },
        children: [],
      },
    ],
  },
].map(withDefaults);
