import { createContextualDate } from "../../DateField/mockData";
import { genPeople } from "../../utils/storybook/genPeople";
import * as Types from "../types";

// Labels removed in current iteration

// Generate a consistent set of people for our mock data
const generatedPeople = genPeople(4);

// Mock people - mapped into an object for easy reference with proper Types.Person typing
export const mockPeople: Record<string, Types.Person> = {
  john: generatedPeople[0]!,
  jane: generatedPeople[1]!,
  bob: generatedPeople[2]!,
  emily: generatedPeople[3]!,
};

// Shared status options for tasks
export const PENDING_STATUS: Types.Status = {
  id: "pending",
  value: "pending",
  label: "Not started",
  color: "gray",
  icon: "circleDashed",
  index: 0,
  closed: false,
};

export const IN_PROGRESS_STATUS: Types.Status = {
  id: "in_progress",
  value: "in_progress",
  label: "In progress",
  color: "blue",
  icon: "circleDot",
  index: 1,
  closed: false,
};

export const DONE_STATUS: Types.Status = {
  id: "done",
  value: "done",
  label: "Done",
  color: "green",
  icon: "circleCheck",
  index: 2,
  closed: true,
};

export const CANCELED_STATUS: Types.Status = {
  id: "canceled",
  value: "canceled",
  label: "Canceled",
  color: "red",
  icon: "circleX",
  index: 3,
  closed: true,
};

// Mock milestones
export const mockMilestones: Record<string, Types.Milestone> = {
  q2Release: {
    id: "1",
    name: "Q2 Release",
    dueDate: createContextualDate("2025-06-30", "day"),
    hasDescription: true,
    hasComments: true,
    commentCount: 5,
    status: "pending",
    link: "#",
  },
  productLaunch: {
    id: "2",
    name: "Product Launch",
    dueDate: createContextualDate("2025-08-15", "day"),
    hasDescription: true,
    hasComments: true,
    commentCount: 3,
    status: "pending",
    link: "#",
  },
  marketExpansion: {
    id: "3",
    name: "Market Expansion",
    dueDate: createContextualDate("2025-09-30", "day"),
    hasDescription: false,
    hasComments: false,
    status: "pending",
    link: "#",
  },
  completedMilestone1: {
    id: "4",
    name: "Initial Research Phase",
    dueDate: createContextualDate("2025-03-15", "day"),
    hasDescription: true,
    hasComments: true,
    commentCount: 8,
    status: "done",
    link: "#",
  },
  completedMilestone2: {
    id: "5",
    name: "Design System Foundation",
    dueDate: createContextualDate("2025-04-30", "day"),
    hasDescription: true,
    hasComments: false,
    status: "done",
    link: "#",
  },
  emptyMilestone: {
    id: "6",
    name: "Empty Milestone",
    dueDate: undefined,
    hasDescription: false,
    hasComments: false,
    status: "pending",
    link: "#",
  },
  minimalMilestone: {
    id: "7",
    name: "Minimal Milestone",
    link: "#",
    dueDate: undefined,
    hasDescription: false,
    hasComments: false,
    status: "pending",
  },
};

// Mock tasks
const longTitleOne =
  "Coordinate cross-functional launch strategy across marketing, sales, support, and product to keep messaging aligned through release";
const longTitleTwo =
  "Document post-launch follow-up plan covering customer outreach, success enablement, analytics tracking, and executive reporting milestones";

export const mockTasks: Types.Task[] = [
  {
    id: "task-1",
    title: "Implement user authentication",
    status: PENDING_STATUS,
    description: "Create login/signup flows with OAuth integration",
    link: "#",
    assignees: [mockPeople.john!],
    milestone: mockMilestones.q2Release!,
    dueDate: createContextualDate("2025-05-10", "day"),
    points: 8,
    hasDescription: true,
    hasComments: true,
    commentCount: 3,
  },
  {
    id: "task-2",
    title: "Fix navigation bug on mobile",
    status: IN_PROGRESS_STATUS,
    description: "Fix responsive navigation issues on mobile devices",
    link: "#",
    assignees: [mockPeople.bob!],
    milestone: mockMilestones.q2Release!,
    dueDate: createContextualDate("2025-05-01", "day"),
    points: 3,
    hasDescription: true,
    hasComments: false,
  },
  {
    id: "task-3",
    title: "Update documentation for API v2",
    status: IN_PROGRESS_STATUS,
    description: "Update API documentation for version 2 release",
    link: "#",
    assignees: [mockPeople.emily!],
    milestone: mockMilestones.q2Release!,
    points: 5,
    hasDescription: true,
    hasComments: true,
    dueDate: null,
  },
  {
    id: "task-4",
    title: "Design marketing landing page",
    status: DONE_STATUS,
    description: null,
    link: "#",
    milestone: mockMilestones.productLaunch!,
    dueDate: null,
    points: 5,
    hasDescription: false,
    hasComments: false,
  },
  {
    id: "task-5",
    title: "Research competitor pricing strategies",
    status: PENDING_STATUS,
    description: null,
    link: "#",
    milestone: mockMilestones.marketExpansion!,
    dueDate: createContextualDate("2025-06-15", "day"),
    points: 3,
    hasDescription: false,
    hasComments: false,
  },
  {
    id: "task-6",
    title: "Implement dark mode toggle",
    status: PENDING_STATUS,
    description: "Implement a dark mode toggle for the application",
    link: "#",
    assignees: [mockPeople.emily!],
    milestone: null,
    dueDate: createContextualDate("2025-05-25", "day"),
    points: 3,
    hasDescription: true,
    hasComments: false,
  },
  {
    id: "task-7",
    title: "Optimize database queries",
    status: IN_PROGRESS_STATUS,
    description: "Optimize database queries for improved performance",
    link: "#",
    assignees: [mockPeople.john!],
    milestone: null,
    dueDate: createContextualDate("2025-04-30", "day"),
    points: 5,
    hasDescription: true,
    hasComments: true,
    commentCount: 5,
  },
  {
    id: "task-8",
    title: "Set up CI/CD pipeline",
    status: DONE_STATUS,
    description: "Set up automated CI/CD pipeline for deployment",
    link: "#",
    assignees: [mockPeople.emily!],
    milestone: mockMilestones.q2Release!,
    dueDate: createContextualDate("2025-04-20", "day"),
    points: 8,
    hasDescription: true,
    hasComments: true,
  },
  {
    id: "task-9",
    title: "Add analytics dashboard",
    status: PENDING_STATUS,
    description: null,
    link: "#",
    milestone: mockMilestones.productLaunch!,
    dueDate: null,
    points: 13,
    hasDescription: false,
    hasComments: false,
  },
  {
    id: "task-10",
    title: "Implement social login options",
    status: IN_PROGRESS_STATUS,
    description: "Add Google, Facebook, and GitHub login options",
    link: "#",
    assignees: [mockPeople.jane!],
    milestone: mockMilestones.q2Release!,
    dueDate: createContextualDate("2025-05-20", "day"),
    points: 5,
    hasDescription: true,
    hasComments: true,
    commentCount: 2,
  },
  {
    id: "task-11",
    title: "Redesign user profile page",
    status: DONE_STATUS,
    description: "Redesign the user profile page with modern UI",
    link: "#",
    assignees: [mockPeople.bob!],
    milestone: mockMilestones.q2Release!,
    dueDate: createContextualDate("2025-04-15", "day"),
    points: 8,
    hasDescription: true,
    hasComments: true,
    commentCount: 7,
  },
  {
    id: "task-12",
    title: "Create A/B testing framework",
    status: CANCELED_STATUS,
    description: null,
    link: "#",
    milestone: mockMilestones.productLaunch!,
    dueDate: null,
    points: 13,
    hasDescription: false,
    hasComments: false,
  },
  {
    id: "task-13",
    title: "Optimize image loading",
    status: IN_PROGRESS_STATUS,
    description: "Optimize image loading performance and lazy loading",
    link: "#",
    assignees: [mockPeople.bob!],
    milestone: mockMilestones.q2Release!,
    dueDate: createContextualDate("2025-05-25", "day"),
    points: 3,
    hasDescription: true,
    hasComments: false,
  },
  {
    id: "task-14",
    title: "Setup internationalization",
    status: PENDING_STATUS,
    description: "Setup i18n framework for multi-language support",
    link: "#",
    assignees: [mockPeople.jane!],
    milestone: mockMilestones.marketExpansion!,
    dueDate: createContextualDate("2025-08-10", "day"),
    points: 8,
    hasDescription: true,
    hasComments: true,
    commentCount: 1,
  },
  {
    id: "task-15",
    title: "Implement payment gateway integration",
    status: DONE_STATUS,
    description: "Integrate Stripe and PayPal payment gateways",
    link: "#",
    assignees: [mockPeople.john!],
    milestone: mockMilestones.productLaunch!,
    dueDate: createContextualDate("2025-06-01", "day"),
    points: 13,
    hasDescription: true,
    hasComments: true,
    commentCount: 9,
  },
  {
    id: "task-16",
    title: "Create automated email campaigns",
    status: PENDING_STATUS,
    description: "Create automated email marketing campaigns",
    link: "#",
    assignees: [mockPeople.emily!],
    milestone: mockMilestones.marketExpansion!,
    dueDate: createContextualDate("2025-07-30", "day"),
    points: 5,
    hasDescription: true,
    hasComments: false,
  },
  {
    id: "task-17",
    title: "Research new features for next quarter",
    status: PENDING_STATUS,
    description: "Research and plan new features for Q3",
    link: "#",
    assignees: [mockPeople.bob!],
    milestone: mockMilestones.marketExpansion!,
    dueDate: createContextualDate("2025-08-15", "day"),
    points: 3,
    hasDescription: true,
    hasComments: false,
  },
  {
    id: "task-18",
    title: "This task demonstrates a minimal milestone",
    status: PENDING_STATUS,
    description: null,
    link: "#",
    assignees: [],
    milestone: mockMilestones.minimalMilestone!,
    dueDate: null,
    points: 0,
    hasDescription: false,
    hasComments: false,
  },
  {
    id: "task-10",
    title: longTitleOne,
    status: IN_PROGRESS_STATUS,
    description: "Weekly syncs ensure every team stays on track",
    link: "#",
    assignees: [mockPeople.jane!],
    milestone: mockMilestones.productLaunch!,
    dueDate: createContextualDate("2025-07-05", "day"),
    points: 8,
    hasDescription: true,
    hasComments: true,
    commentCount: 4,
  },
  {
    id: "task-11",
    title: longTitleTwo,
    status: PENDING_STATUS,
    description: "Outline responsibilities for each team once the launch ships",
    link: "#",
    assignees: [mockPeople.emily!],
    milestone: mockMilestones.marketExpansion!,
    dueDate: createContextualDate("2025-07-20", "day"),
    points: 5,
    hasDescription: true,
    hasComments: false,
  },
];

// Mock empty tasks array
export const mockEmptyTasks: Types.Task[] = [];
