//
// Automatically generated by mix operately.gen.page.index
// Do not edit this file directly
//

import * as AccountAppearancePage from "./AccountAppearancePage";
import * as AccountEditProfilePage from "./AccountEditProfilePage";
import * as AccountNotificationSettingsPage from "./AccountNotificationSettingsPage";
import * as AccountPage from "./AccountPage";
import * as CompanyAdminAddPeoplePage from "./CompanyAdminAddPeoplePage";
import * as CompanyAdminManageAdminsPage from "./CompanyAdminManageAdminsPage";
import * as CompanyAdminManagePeoplePage from "./CompanyAdminManagePeoplePage";
import * as CompanyAdminPage from "./CompanyAdminPage";
import * as CompanyAdminTrustedEmailDomainsPage from "./CompanyAdminTrustedEmailDomainsPage";
import * as DiscussionEditPage from "./DiscussionEditPage";
import * as DiscussionNewPage from "./DiscussionNewPage";
import * as DiscussionPage from "./DiscussionPage";
import * as FeedPage from "./FeedPage";
import * as GoalAboutPage from "./GoalAboutPage";
import * as GoalActivityPage from "./GoalActivityPage";
import * as GoalAddPage from "./GoalAddPage";
import * as GoalArchivePage from "./GoalArchivePage";
import * as GoalClosingPage from "./GoalClosingPage";
import * as GoalDiscussionEditPage from "./GoalDiscussionEditPage";
import * as GoalDiscussionNewPage from "./GoalDiscussionNewPage";
import * as GoalDiscussionsPage from "./GoalDiscussionsPage";
import * as GoalEditPage from "./GoalEditPage";
import * as GoalEditParentPage from "./GoalEditParentPage";
import * as GoalEditTimeframePage from "./GoalEditTimeframePage";
import * as GoalPage from "./GoalPage";
import * as GoalProgressUpdateEditPage from "./GoalProgressUpdateEditPage";
import * as GoalProgressUpdateNewPage from "./GoalProgressUpdateNewPage";
import * as GoalProgressUpdatePage from "./GoalProgressUpdatePage";
import * as GoalReopenPage from "./GoalReopenPage";
import * as GoalSubgoalsPage from "./GoalSubgoalsPage";
import * as GoalsPage from "./GoalsPage";
import * as GroupAddPage from "./GroupAddPage";
import * as GroupAppearancePage from "./GroupAppearancePage";
import * as GroupDiscussionsPage from "./GroupDiscussionsPage";
import * as GroupEditPage from "./GroupEditPage";
import * as GroupGoalsPage from "./GroupGoalsPage";
import * as GroupListPage from "./GroupListPage";
import * as GroupMembersPage from "./GroupMembersPage";
import * as GroupPage from "./GroupPage";
import * as GroupProjectsPage from "./GroupProjectsPage";
import * as NotFoundPage from "./NotFoundPage";
import * as NotificationsPage from "./NotificationsPage";
import * as PeopleOrgChartPage from "./PeopleOrgChartPage";
import * as PeoplePage from "./PeoplePage";
import * as ProfileGoalsPage from "./ProfileGoalsPage";
import * as ProfilePage from "./ProfilePage";
import * as ProjectAddPage from "./ProjectAddPage";
import * as ProjectAddResourcePage from "./ProjectAddResourcePage";
import * as ProjectArchivationPage from "./ProjectArchivationPage";
import * as ProjectCheckInEditPage from "./ProjectCheckInEditPage";
import * as ProjectCheckInNewPage from "./ProjectCheckInNewPage";
import * as ProjectCheckInPage from "./ProjectCheckInPage";
import * as ProjectCheckInsPage from "./ProjectCheckInsPage";
import * as ProjectClosePage from "./ProjectClosePage";
import * as ProjectContributorsPage from "./ProjectContributorsPage";
import * as ProjectEditDescriptionPage from "./ProjectEditDescriptionPage";
import * as ProjectEditGoalPage from "./ProjectEditGoalPage";
import * as ProjectEditProjectNamePage from "./ProjectEditProjectNamePage";
import * as ProjectEditResourcePage from "./ProjectEditResourcePage";
import * as ProjectEditResourcesPage from "./ProjectEditResourcesPage";
import * as ProjectEditTimelinePage from "./ProjectEditTimelinePage";
import * as ProjectMilestonePage from "./ProjectMilestonePage";
import * as ProjectMilestonesPage from "./ProjectMilestonesPage";
import * as ProjectMovePage from "./ProjectMovePage";
import * as ProjectPage from "./ProjectPage";
import * as ProjectPausePage from "./ProjectPausePage";
import * as ProjectResumePage from "./ProjectResumePage";
import * as ProjectRetrospectivePage from "./ProjectRetrospectivePage";
import * as ProjectsPage from "./ProjectsPage";
import * as TaskPage from "./TaskPage";

//
// We are explocily exporting the pages here to avoid false positives
// dead code repors form knip
//
export default {
  AccountAppearancePage: {
    loader: AccountAppearancePage.loader,
    Page: AccountAppearancePage.Page
  },
  AccountEditProfilePage: {
    loader: AccountEditProfilePage.loader,
    Page: AccountEditProfilePage.Page
  },
  AccountNotificationSettingsPage: {
    loader: AccountNotificationSettingsPage.loader,
    Page: AccountNotificationSettingsPage.Page
  },
  AccountPage: {
    loader: AccountPage.loader,
    Page: AccountPage.Page
  },
  CompanyAdminAddPeoplePage: {
    loader: CompanyAdminAddPeoplePage.loader,
    Page: CompanyAdminAddPeoplePage.Page
  },
  CompanyAdminManageAdminsPage: {
    loader: CompanyAdminManageAdminsPage.loader,
    Page: CompanyAdminManageAdminsPage.Page
  },
  CompanyAdminManagePeoplePage: {
    loader: CompanyAdminManagePeoplePage.loader,
    Page: CompanyAdminManagePeoplePage.Page
  },
  CompanyAdminPage: {
    loader: CompanyAdminPage.loader,
    Page: CompanyAdminPage.Page
  },
  CompanyAdminTrustedEmailDomainsPage: {
    loader: CompanyAdminTrustedEmailDomainsPage.loader,
    Page: CompanyAdminTrustedEmailDomainsPage.Page
  },
  DiscussionEditPage: {
    loader: DiscussionEditPage.loader,
    Page: DiscussionEditPage.Page
  },
  DiscussionNewPage: {
    loader: DiscussionNewPage.loader,
    Page: DiscussionNewPage.Page
  },
  DiscussionPage: {
    loader: DiscussionPage.loader,
    Page: DiscussionPage.Page
  },
  FeedPage: {
    loader: FeedPage.loader,
    Page: FeedPage.Page
  },
  GoalAboutPage: {
    loader: GoalAboutPage.loader,
    Page: GoalAboutPage.Page
  },
  GoalActivityPage: {
    loader: GoalActivityPage.loader,
    Page: GoalActivityPage.Page
  },
  GoalAddPage: {
    loader: GoalAddPage.loader,
    Page: GoalAddPage.Page
  },
  GoalArchivePage: {
    loader: GoalArchivePage.loader,
    Page: GoalArchivePage.Page
  },
  GoalClosingPage: {
    loader: GoalClosingPage.loader,
    Page: GoalClosingPage.Page
  },
  GoalDiscussionEditPage: {
    loader: GoalDiscussionEditPage.loader,
    Page: GoalDiscussionEditPage.Page
  },
  GoalDiscussionNewPage: {
    loader: GoalDiscussionNewPage.loader,
    Page: GoalDiscussionNewPage.Page
  },
  GoalDiscussionsPage: {
    loader: GoalDiscussionsPage.loader,
    Page: GoalDiscussionsPage.Page
  },
  GoalEditPage: {
    loader: GoalEditPage.loader,
    Page: GoalEditPage.Page
  },
  GoalEditParentPage: {
    loader: GoalEditParentPage.loader,
    Page: GoalEditParentPage.Page
  },
  GoalEditTimeframePage: {
    loader: GoalEditTimeframePage.loader,
    Page: GoalEditTimeframePage.Page
  },
  GoalPage: {
    loader: GoalPage.loader,
    Page: GoalPage.Page
  },
  GoalProgressUpdateEditPage: {
    loader: GoalProgressUpdateEditPage.loader,
    Page: GoalProgressUpdateEditPage.Page
  },
  GoalProgressUpdateNewPage: {
    loader: GoalProgressUpdateNewPage.loader,
    Page: GoalProgressUpdateNewPage.Page
  },
  GoalProgressUpdatePage: {
    loader: GoalProgressUpdatePage.loader,
    Page: GoalProgressUpdatePage.Page
  },
  GoalReopenPage: {
    loader: GoalReopenPage.loader,
    Page: GoalReopenPage.Page
  },
  GoalSubgoalsPage: {
    loader: GoalSubgoalsPage.loader,
    Page: GoalSubgoalsPage.Page
  },
  GoalsPage: {
    loader: GoalsPage.loader,
    Page: GoalsPage.Page
  },
  GroupAddPage: {
    loader: GroupAddPage.loader,
    Page: GroupAddPage.Page
  },
  GroupAppearancePage: {
    loader: GroupAppearancePage.loader,
    Page: GroupAppearancePage.Page
  },
  GroupDiscussionsPage: {
    loader: GroupDiscussionsPage.loader,
    Page: GroupDiscussionsPage.Page
  },
  GroupEditPage: {
    loader: GroupEditPage.loader,
    Page: GroupEditPage.Page
  },
  GroupGoalsPage: {
    loader: GroupGoalsPage.loader,
    Page: GroupGoalsPage.Page
  },
  GroupListPage: {
    loader: GroupListPage.loader,
    Page: GroupListPage.Page
  },
  GroupMembersPage: {
    loader: GroupMembersPage.loader,
    Page: GroupMembersPage.Page
  },
  GroupPage: {
    loader: GroupPage.loader,
    Page: GroupPage.Page
  },
  GroupProjectsPage: {
    loader: GroupProjectsPage.loader,
    Page: GroupProjectsPage.Page
  },
  NotFoundPage: {
    loader: NotFoundPage.loader,
    Page: NotFoundPage.Page
  },
  NotificationsPage: {
    loader: NotificationsPage.loader,
    Page: NotificationsPage.Page
  },
  PeopleOrgChartPage: {
    loader: PeopleOrgChartPage.loader,
    Page: PeopleOrgChartPage.Page
  },
  PeoplePage: {
    loader: PeoplePage.loader,
    Page: PeoplePage.Page
  },
  ProfileGoalsPage: {
    loader: ProfileGoalsPage.loader,
    Page: ProfileGoalsPage.Page
  },
  ProfilePage: {
    loader: ProfilePage.loader,
    Page: ProfilePage.Page
  },
  ProjectAddPage: {
    loader: ProjectAddPage.loader,
    Page: ProjectAddPage.Page
  },
  ProjectAddResourcePage: {
    loader: ProjectAddResourcePage.loader,
    Page: ProjectAddResourcePage.Page
  },
  ProjectArchivationPage: {
    loader: ProjectArchivationPage.loader,
    Page: ProjectArchivationPage.Page
  },
  ProjectCheckInEditPage: {
    loader: ProjectCheckInEditPage.loader,
    Page: ProjectCheckInEditPage.Page
  },
  ProjectCheckInNewPage: {
    loader: ProjectCheckInNewPage.loader,
    Page: ProjectCheckInNewPage.Page
  },
  ProjectCheckInPage: {
    loader: ProjectCheckInPage.loader,
    Page: ProjectCheckInPage.Page
  },
  ProjectCheckInsPage: {
    loader: ProjectCheckInsPage.loader,
    Page: ProjectCheckInsPage.Page
  },
  ProjectClosePage: {
    loader: ProjectClosePage.loader,
    Page: ProjectClosePage.Page
  },
  ProjectContributorsPage: {
    loader: ProjectContributorsPage.loader,
    Page: ProjectContributorsPage.Page
  },
  ProjectEditDescriptionPage: {
    loader: ProjectEditDescriptionPage.loader,
    Page: ProjectEditDescriptionPage.Page
  },
  ProjectEditGoalPage: {
    loader: ProjectEditGoalPage.loader,
    Page: ProjectEditGoalPage.Page
  },
  ProjectEditProjectNamePage: {
    loader: ProjectEditProjectNamePage.loader,
    Page: ProjectEditProjectNamePage.Page
  },
  ProjectEditResourcePage: {
    loader: ProjectEditResourcePage.loader,
    Page: ProjectEditResourcePage.Page
  },
  ProjectEditResourcesPage: {
    loader: ProjectEditResourcesPage.loader,
    Page: ProjectEditResourcesPage.Page
  },
  ProjectEditTimelinePage: {
    loader: ProjectEditTimelinePage.loader,
    Page: ProjectEditTimelinePage.Page
  },
  ProjectMilestonePage: {
    loader: ProjectMilestonePage.loader,
    Page: ProjectMilestonePage.Page
  },
  ProjectMilestonesPage: {
    loader: ProjectMilestonesPage.loader,
    Page: ProjectMilestonesPage.Page
  },
  ProjectMovePage: {
    loader: ProjectMovePage.loader,
    Page: ProjectMovePage.Page
  },
  ProjectPage: {
    loader: ProjectPage.loader,
    Page: ProjectPage.Page
  },
  ProjectPausePage: {
    loader: ProjectPausePage.loader,
    Page: ProjectPausePage.Page
  },
  ProjectResumePage: {
    loader: ProjectResumePage.loader,
    Page: ProjectResumePage.Page
  },
  ProjectRetrospectivePage: {
    loader: ProjectRetrospectivePage.loader,
    Page: ProjectRetrospectivePage.Page
  },
  ProjectsPage: {
    loader: ProjectsPage.loader,
    Page: ProjectsPage.Page
  },
  TaskPage: {
    loader: TaskPage.loader,
    Page: TaskPage.Page
  }
};
