//
// Automatically generated by mix operately.gen.page.index
// Do not edit this file directly
//

import * as AccountAppearancePage from "./AccountAppearancePage";
import * as AccountEditProfilePage from "./AccountEditProfilePage";
import * as AccountNotificationSettingsPage from "./AccountNotificationSettingsPage";
import * as AccountPage from "./AccountPage";
import * as Company from "./Company";
import * as GroupAddPage from "./GroupAddPage";
import * as GroupAppearancePage from "./GroupAppearancePage";
import * as GroupListPage from "./GroupListPage";
import * as GroupMembersPage from "./GroupMembersPage";
import * as GroupPage from "./GroupPage";
import * as HomePage from "./HomePage";
import * as KpiListPage from "./KpiListPage";
import * as KpiPage from "./KpiPage";
import * as MyAssignmentsPage from "./MyAssignmentsPage";
import * as NotFoundPage from "./NotFoundPage";
import * as NotificationsPage from "./NotificationsPage";
import * as ObjectiveListPage from "./ObjectiveListPage";
import * as ObjectivePage from "./ObjectivePage";
import * as ProfilePage from "./ProfilePage";
import * as ProjectAddPage from "./ProjectAddPage";
import * as ProjectArchivationPage from "./ProjectArchivationPage";
import * as ProjectContributorsPage from "./ProjectContributorsPage";
import * as ProjectDiscussionNewPage from "./ProjectDiscussionNewPage";
import * as ProjectDiscussionPage from "./ProjectDiscussionPage";
import * as ProjectEditDescriptionPage from "./ProjectEditDescriptionPage";
import * as ProjectEditProjectNamePage from "./ProjectEditProjectNamePage";
import * as ProjectEditResourcesPage from "./ProjectEditResourcesPage";
import * as ProjectEditTimelinePage from "./ProjectEditTimelinePage";
import * as ProjectMilestonePage from "./ProjectMilestonePage";
import * as ProjectMilestonesPage from "./ProjectMilestonesPage";
import * as ProjectMovePage from "./ProjectMovePage";
import * as ProjectPage from "./ProjectPage";
import * as ProjectPhaseChangeSurveyPage from "./ProjectPhaseChangeSurveyPage";
import * as ProjectReviewPage from "./ProjectReviewPage";
import * as ProjectReviewRequestNewPage from "./ProjectReviewRequestNewPage";
import * as ProjectReviewRequestPage from "./ProjectReviewRequestPage";
import * as ProjectReviewRequestSubmitPage from "./ProjectReviewRequestSubmitPage";
import * as ProjectStatusUpdateListPage from "./ProjectStatusUpdateListPage";
import * as ProjectStatusUpdateNewPage from "./ProjectStatusUpdateNewPage";
import * as ProjectStatusUpdatePage from "./ProjectStatusUpdatePage";
import * as TenetListPage from "./TenetListPage";
import * as TenetPage from "./TenetPage";

export default {
  AccountAppearancePage,
  AccountEditProfilePage,
  AccountNotificationSettingsPage,
  AccountPage,
  Company,
  GroupAddPage,
  GroupAppearancePage,
  GroupListPage,
  GroupMembersPage,
  GroupPage,
  HomePage,
  KpiListPage,
  KpiPage,
  MyAssignmentsPage,
  NotFoundPage,
  NotificationsPage,
  ObjectiveListPage,
  ObjectivePage,
  ProfilePage,
  ProjectAddPage,
  ProjectArchivationPage,
  ProjectContributorsPage,
  ProjectDiscussionNewPage,
  ProjectDiscussionPage,
  ProjectEditDescriptionPage,
  ProjectEditProjectNamePage,
  ProjectEditResourcesPage,
  ProjectEditTimelinePage,
  ProjectMilestonePage,
  ProjectMilestonesPage,
  ProjectMovePage,
  ProjectPage,
  ProjectPhaseChangeSurveyPage,
  ProjectReviewPage,
  ProjectReviewRequestNewPage,
  ProjectReviewRequestPage,
  ProjectReviewRequestSubmitPage,
  ProjectStatusUpdateListPage,
  ProjectStatusUpdateNewPage,
  ProjectStatusUpdatePage,
  TenetListPage,
  TenetPage
};
