//
// Automatically generated by mix operately.gen.page.index
// Do not edit this file directly
//

import * as AccountAppearancePage from "./AccountAppearancePage";
import * as AccountEditProfilePage from "./AccountEditProfilePage";
import * as AccountNotificationSettingsPage from "./AccountNotificationSettingsPage";
import * as AccountPage from "./AccountPage";
import * as CompanyAdminAddPeoplePage from "./CompanyAdminAddPeoplePage";
import * as CompanyAdminManageAdminsPage from "./CompanyAdminManageAdminsPage";
import * as CompanyAdminManagePeoplePage from "./CompanyAdminManagePeoplePage";
import * as CompanyAdminPage from "./CompanyAdminPage";
import * as CompanyAdminTrustedEmailDomainsPage from "./CompanyAdminTrustedEmailDomainsPage";
import * as DiscussionNewPage from "./DiscussionNewPage";
import * as DiscussionPage from "./DiscussionPage";
import * as GoalAddPage from "./GoalAddPage";
import * as GoalArchivePage from "./GoalArchivePage";
import * as GoalCheckInPage from "./GoalCheckInPage";
import * as GoalCheckInsPage from "./GoalCheckInsPage";
import * as GoalEditPage from "./GoalEditPage";
import * as GoalNewCheckInPage from "./GoalNewCheckInPage";
import * as GoalPage from "./GoalPage";
import * as GoalsPage from "./GoalsPage";
import * as GroupAddPage from "./GroupAddPage";
import * as GroupAppearancePage from "./GroupAppearancePage";
import * as GroupDiscussionsPage from "./GroupDiscussionsPage";
import * as GroupEditPage from "./GroupEditPage";
import * as GroupGoalsPage from "./GroupGoalsPage";
import * as GroupKpisPage from "./GroupKpisPage";
import * as GroupListPage from "./GroupListPage";
import * as GroupMembersPage from "./GroupMembersPage";
import * as GroupPage from "./GroupPage";
import * as GroupProjectsPage from "./GroupProjectsPage";
import * as MyAssignmentsPage from "./MyAssignmentsPage";
import * as NotFoundPage from "./NotFoundPage";
import * as NotificationsPage from "./NotificationsPage";
import * as PeopleOrgChartPage from "./PeopleOrgChartPage";
import * as PeoplePage from "./PeoplePage";
import * as ProfilePage from "./ProfilePage";
import * as ProjectAddPage from "./ProjectAddPage";
import * as ProjectAddResourcePage from "./ProjectAddResourcePage";
import * as ProjectArchivationPage from "./ProjectArchivationPage";
import * as ProjectClosePage from "./ProjectClosePage";
import * as ProjectContributorsPage from "./ProjectContributorsPage";
import * as ProjectEditDescriptionPage from "./ProjectEditDescriptionPage";
import * as ProjectEditGoalPage from "./ProjectEditGoalPage";
import * as ProjectEditProjectNamePage from "./ProjectEditProjectNamePage";
import * as ProjectEditResourcePage from "./ProjectEditResourcePage";
import * as ProjectEditResourcesPage from "./ProjectEditResourcesPage";
import * as ProjectEditTimelinePage from "./ProjectEditTimelinePage";
import * as ProjectMilestonePage from "./ProjectMilestonePage";
import * as ProjectMilestonesPage from "./ProjectMilestonesPage";
import * as ProjectMovePage from "./ProjectMovePage";
import * as ProjectPage from "./ProjectPage";
import * as ProjectPhaseChangeSurveyPage from "./ProjectPhaseChangeSurveyPage";
import * as ProjectRetrospectivePage from "./ProjectRetrospectivePage";
import * as ProjectReviewPage from "./ProjectReviewPage";
import * as ProjectReviewRequestNewPage from "./ProjectReviewRequestNewPage";
import * as ProjectReviewRequestPage from "./ProjectReviewRequestPage";
import * as ProjectReviewRequestSubmitPage from "./ProjectReviewRequestSubmitPage";
import * as ProjectStatusUpdateEditPage from "./ProjectStatusUpdateEditPage";
import * as ProjectStatusUpdateListPage from "./ProjectStatusUpdateListPage";
import * as ProjectStatusUpdateNewPage from "./ProjectStatusUpdateNewPage";
import * as ProjectStatusUpdatePage from "./ProjectStatusUpdatePage";
import * as ProjectsPage from "./ProjectsPage";

//
// We are explocily exporting the pages here to avoid false positives
// dead code repors form knip
//
export default {
  AccountAppearancePage: {
    loader: AccountAppearancePage.loader,
    Page: AccountAppearancePage.Page
  },
  AccountEditProfilePage: {
    loader: AccountEditProfilePage.loader,
    Page: AccountEditProfilePage.Page
  },
  AccountNotificationSettingsPage: {
    loader: AccountNotificationSettingsPage.loader,
    Page: AccountNotificationSettingsPage.Page
  },
  AccountPage: {
    loader: AccountPage.loader,
    Page: AccountPage.Page
  },
  CompanyAdminAddPeoplePage: {
    loader: CompanyAdminAddPeoplePage.loader,
    Page: CompanyAdminAddPeoplePage.Page
  },
  CompanyAdminManageAdminsPage: {
    loader: CompanyAdminManageAdminsPage.loader,
    Page: CompanyAdminManageAdminsPage.Page
  },
  CompanyAdminManagePeoplePage: {
    loader: CompanyAdminManagePeoplePage.loader,
    Page: CompanyAdminManagePeoplePage.Page
  },
  CompanyAdminPage: {
    loader: CompanyAdminPage.loader,
    Page: CompanyAdminPage.Page
  },
  CompanyAdminTrustedEmailDomainsPage: {
    loader: CompanyAdminTrustedEmailDomainsPage.loader,
    Page: CompanyAdminTrustedEmailDomainsPage.Page
  },
  DiscussionNewPage: {
    loader: DiscussionNewPage.loader,
    Page: DiscussionNewPage.Page
  },
  DiscussionPage: {
    loader: DiscussionPage.loader,
    Page: DiscussionPage.Page
  },
  GoalAddPage: {
    loader: GoalAddPage.loader,
    Page: GoalAddPage.Page
  },
  GoalArchivePage: {
    loader: GoalArchivePage.loader,
    Page: GoalArchivePage.Page
  },
  GoalCheckInPage: {
    loader: GoalCheckInPage.loader,
    Page: GoalCheckInPage.Page
  },
  GoalCheckInsPage: {
    loader: GoalCheckInsPage.loader,
    Page: GoalCheckInsPage.Page
  },
  GoalEditPage: {
    loader: GoalEditPage.loader,
    Page: GoalEditPage.Page
  },
  GoalNewCheckInPage: {
    loader: GoalNewCheckInPage.loader,
    Page: GoalNewCheckInPage.Page
  },
  GoalPage: {
    loader: GoalPage.loader,
    Page: GoalPage.Page
  },
  GoalsPage: {
    loader: GoalsPage.loader,
    Page: GoalsPage.Page
  },
  GroupAddPage: {
    loader: GroupAddPage.loader,
    Page: GroupAddPage.Page
  },
  GroupAppearancePage: {
    loader: GroupAppearancePage.loader,
    Page: GroupAppearancePage.Page
  },
  GroupDiscussionsPage: {
    loader: GroupDiscussionsPage.loader,
    Page: GroupDiscussionsPage.Page
  },
  GroupEditPage: {
    loader: GroupEditPage.loader,
    Page: GroupEditPage.Page
  },
  GroupGoalsPage: {
    loader: GroupGoalsPage.loader,
    Page: GroupGoalsPage.Page
  },
  GroupKpisPage: {
    loader: GroupKpisPage.loader,
    Page: GroupKpisPage.Page
  },
  GroupListPage: {
    loader: GroupListPage.loader,
    Page: GroupListPage.Page
  },
  GroupMembersPage: {
    loader: GroupMembersPage.loader,
    Page: GroupMembersPage.Page
  },
  GroupPage: {
    loader: GroupPage.loader,
    Page: GroupPage.Page
  },
  GroupProjectsPage: {
    loader: GroupProjectsPage.loader,
    Page: GroupProjectsPage.Page
  },
  MyAssignmentsPage: {
    loader: MyAssignmentsPage.loader,
    Page: MyAssignmentsPage.Page
  },
  NotFoundPage: {
    loader: NotFoundPage.loader,
    Page: NotFoundPage.Page
  },
  NotificationsPage: {
    loader: NotificationsPage.loader,
    Page: NotificationsPage.Page
  },
  PeopleOrgChartPage: {
    loader: PeopleOrgChartPage.loader,
    Page: PeopleOrgChartPage.Page
  },
  PeoplePage: {
    loader: PeoplePage.loader,
    Page: PeoplePage.Page
  },
  ProfilePage: {
    loader: ProfilePage.loader,
    Page: ProfilePage.Page
  },
  ProjectAddPage: {
    loader: ProjectAddPage.loader,
    Page: ProjectAddPage.Page
  },
  ProjectAddResourcePage: {
    loader: ProjectAddResourcePage.loader,
    Page: ProjectAddResourcePage.Page
  },
  ProjectArchivationPage: {
    loader: ProjectArchivationPage.loader,
    Page: ProjectArchivationPage.Page
  },
  ProjectClosePage: {
    loader: ProjectClosePage.loader,
    Page: ProjectClosePage.Page
  },
  ProjectContributorsPage: {
    loader: ProjectContributorsPage.loader,
    Page: ProjectContributorsPage.Page
  },
  ProjectEditDescriptionPage: {
    loader: ProjectEditDescriptionPage.loader,
    Page: ProjectEditDescriptionPage.Page
  },
  ProjectEditGoalPage: {
    loader: ProjectEditGoalPage.loader,
    Page: ProjectEditGoalPage.Page
  },
  ProjectEditProjectNamePage: {
    loader: ProjectEditProjectNamePage.loader,
    Page: ProjectEditProjectNamePage.Page
  },
  ProjectEditResourcePage: {
    loader: ProjectEditResourcePage.loader,
    Page: ProjectEditResourcePage.Page
  },
  ProjectEditResourcesPage: {
    loader: ProjectEditResourcesPage.loader,
    Page: ProjectEditResourcesPage.Page
  },
  ProjectEditTimelinePage: {
    loader: ProjectEditTimelinePage.loader,
    Page: ProjectEditTimelinePage.Page
  },
  ProjectMilestonePage: {
    loader: ProjectMilestonePage.loader,
    Page: ProjectMilestonePage.Page
  },
  ProjectMilestonesPage: {
    loader: ProjectMilestonesPage.loader,
    Page: ProjectMilestonesPage.Page
  },
  ProjectMovePage: {
    loader: ProjectMovePage.loader,
    Page: ProjectMovePage.Page
  },
  ProjectPage: {
    loader: ProjectPage.loader,
    Page: ProjectPage.Page
  },
  ProjectPhaseChangeSurveyPage: {
    loader: ProjectPhaseChangeSurveyPage.loader,
    Page: ProjectPhaseChangeSurveyPage.Page
  },
  ProjectRetrospectivePage: {
    loader: ProjectRetrospectivePage.loader,
    Page: ProjectRetrospectivePage.Page
  },
  ProjectReviewPage: {
    loader: ProjectReviewPage.loader,
    Page: ProjectReviewPage.Page
  },
  ProjectReviewRequestNewPage: {
    loader: ProjectReviewRequestNewPage.loader,
    Page: ProjectReviewRequestNewPage.Page
  },
  ProjectReviewRequestPage: {
    loader: ProjectReviewRequestPage.loader,
    Page: ProjectReviewRequestPage.Page
  },
  ProjectReviewRequestSubmitPage: {
    loader: ProjectReviewRequestSubmitPage.loader,
    Page: ProjectReviewRequestSubmitPage.Page
  },
  ProjectStatusUpdateEditPage: {
    loader: ProjectStatusUpdateEditPage.loader,
    Page: ProjectStatusUpdateEditPage.Page
  },
  ProjectStatusUpdateListPage: {
    loader: ProjectStatusUpdateListPage.loader,
    Page: ProjectStatusUpdateListPage.Page
  },
  ProjectStatusUpdateNewPage: {
    loader: ProjectStatusUpdateNewPage.loader,
    Page: ProjectStatusUpdateNewPage.Page
  },
  ProjectStatusUpdatePage: {
    loader: ProjectStatusUpdatePage.loader,
    Page: ProjectStatusUpdatePage.Page
  },
  ProjectsPage: {
    loader: ProjectsPage.loader,
    Page: ProjectsPage.Page
  }
};
