defmodule OperatelyWeb.Graphql.Schema do
  #
  # This file is generated by: mix operately.gen.elixir.graphql.schema
  # Do not edit this file directly.
  #

  use Absinthe.Schema

  import_types Absinthe.Type.Custom

  # Types
  import_types OperatelyWeb.Graphql.Types.Activities
  import_types OperatelyWeb.Graphql.Types.ActivityContentProjectDiscussionSubmitted
  import_types OperatelyWeb.Graphql.Types.Assignments
  import_types OperatelyWeb.Graphql.Types.Blobs
  import_types OperatelyWeb.Graphql.Types.Comments
  import_types OperatelyWeb.Graphql.Types.Companies
  import_types OperatelyWeb.Graphql.Types.Dashboards
  import_types OperatelyWeb.Graphql.Types.Groups
  import_types OperatelyWeb.Graphql.Types.KeyResults
  import_types OperatelyWeb.Graphql.Types.Kpis
  import_types OperatelyWeb.Graphql.Types.Milestones
  import_types OperatelyWeb.Graphql.Types.Notifications
  import_types OperatelyWeb.Graphql.Types.Objectives
  import_types OperatelyWeb.Graphql.Types.Person
  import_types OperatelyWeb.Graphql.Types.ProjectReviewRequests
  import_types OperatelyWeb.Graphql.Types.Projects
  import_types OperatelyWeb.Graphql.Types.Reactions
  import_types OperatelyWeb.Graphql.Types.Tenets
  import_types OperatelyWeb.Graphql.Types.UpdateContentMessage
  import_types OperatelyWeb.Graphql.Types.UpdateContentProjectContributorAdded
  import_types OperatelyWeb.Graphql.Types.UpdateContentProjectContributorRemoved
  import_types OperatelyWeb.Graphql.Types.UpdateContentProjectCreated
  import_types OperatelyWeb.Graphql.Types.UpdateContentProjectDiscussion
  import_types OperatelyWeb.Graphql.Types.UpdateContentProjectEndTimeChanged
  import_types OperatelyWeb.Graphql.Types.UpdateContentProjectMilestoneCompleted
  import_types OperatelyWeb.Graphql.Types.UpdateContentProjectMilestoneCreated
  import_types OperatelyWeb.Graphql.Types.UpdateContentProjectMilestoneDeadlineChanged
  import_types OperatelyWeb.Graphql.Types.UpdateContentProjectMilestoneDeleted
  import_types OperatelyWeb.Graphql.Types.UpdateContentProjectStartTimeChanged
  import_types OperatelyWeb.Graphql.Types.UpdateContentReview
  import_types OperatelyWeb.Graphql.Types.UpdateContentStatusUpdate
  import_types OperatelyWeb.Graphql.Types.Updates

  # Queries
  import_types OperatelyWeb.Graphql.Queries.Activities
  import_types OperatelyWeb.Graphql.Queries.Assignments
  import_types OperatelyWeb.Graphql.Queries.Companies
  import_types OperatelyWeb.Graphql.Queries.Groups
  import_types OperatelyWeb.Graphql.Queries.KeyResults
  import_types OperatelyWeb.Graphql.Queries.Kpis
  import_types OperatelyWeb.Graphql.Queries.Milestones
  import_types OperatelyWeb.Graphql.Queries.Notifications
  import_types OperatelyWeb.Graphql.Queries.Objectives
  import_types OperatelyWeb.Graphql.Queries.People
  import_types OperatelyWeb.Graphql.Queries.ProjectReviewRequests
  import_types OperatelyWeb.Graphql.Queries.Projects
  import_types OperatelyWeb.Graphql.Queries.Tenets
  import_types OperatelyWeb.Graphql.Queries.Updates

  # Mutations
  import_types OperatelyWeb.Graphql.Mutations.Blobs
  import_types OperatelyWeb.Graphql.Mutations.Dashboards
  import_types OperatelyWeb.Graphql.Mutations.Groups
  import_types OperatelyWeb.Graphql.Mutations.KeyResults
  import_types OperatelyWeb.Graphql.Mutations.Kpis
  import_types OperatelyWeb.Graphql.Mutations.Milestones
  import_types OperatelyWeb.Graphql.Mutations.Notifications
  import_types OperatelyWeb.Graphql.Mutations.Objectives
  import_types OperatelyWeb.Graphql.Mutations.People
  import_types OperatelyWeb.Graphql.Mutations.ProjectReviewRequests
  import_types OperatelyWeb.Graphql.Mutations.Projects
  import_types OperatelyWeb.Graphql.Mutations.Tenets
  import_types OperatelyWeb.Graphql.Mutations.Updates

  # Subscriptions
  import_types OperatelyWeb.Graphql.Subscriptions.Notifications

  query do
    import_fields :activity_queries
    import_fields :assignment_queries
    import_fields :company_queries
    import_fields :group_queries
    import_fields :key_result_queries
    import_fields :kpi_queries
    import_fields :milestone_queries
    import_fields :notification_queries
    import_fields :objective_queries
    import_fields :person_queries
    import_fields :project_review_request_queries
    import_fields :project_queries
    import_fields :tenet_queries
    import_fields :update_queries
  end

  mutation do
    import_fields :blob_mutations
    import_fields :dashboard_mutations
    import_fields :group_mutations
    import_fields :key_result_mutations
    import_fields :kpi_mutations
    import_fields :milestone_mutations
    import_fields :notification_mutations
    import_fields :objective_mutations
    import_fields :person_mutations
    import_fields :project_review_request_mutations
    import_fields :project_mutations
    import_fields :tenet_mutations
    import_fields :update_mutations
  end

  subscription do
    import_fields :notification_subscriptions
  end
end
