defmodule Mix.Tasks.Operately.Gen.Feed.Items.Index do
  import Mix.Operately, only: [generate_file!: 2, list_files: 3]

  @path "assets/js/features/Feed/FeedItems"
  @pattern @path <> "/*.tsx"

  def run(_args) do
    types = list_files(@pattern, :basename, exclude: ["index"])

    generate_index(types)
  end

  def generate_index(types) do
    generate_file!("#{@path}/index.tsx", fn _path ->
      """
      //
      // Automatically generated with mix operate.gen.feed.items.index
      // Do not edit this file manually
      //

      import { FeedItem } from "../FeedItem";

      #{import_types(types)}

      const FeedItems : FeedItem[] = [
      #{types |> Enum.map(fn type -> "  #{type}" end) |> Enum.join(",\n")}
      ];

      export default FeedItems;
      """
    end)
  end

  def import_types(types) do
    types
    |> Enum.map(fn type -> "import { #{type} } from \"./#{type}\"" end)
    |> Enum.join("\n")
  end

end
