import type { Meta, StoryObj } from "@storybook/react";
import { WorkMapTable } from "./WorkMapTable";
import { WorkMap } from ".";
import { currentYear, currentQuarter, currentMonth } from "../TimeframeSelector/utils";

// --- Mock Data ---
function genAvatar(id: string) {
  return `https://images.unsplash.com/${id}?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80`;
}

// People used consistently throughout the stories
const people = {
  igor: {
    id: "user-igor",
    fullName: "Igor Š.",
    avatarUrl: genAvatar("photo-1500648767791-00dcc994a43e"),
  },
  jane: {
    id: "user-jane",
    fullName: "Jane D.",
    avatarUrl: genAvatar("photo-1438761681033-6461ffad8d80"),
  },
  jennifer: {
    id: "user-jennifer",
    fullName: "Jennifer L.",
    avatarUrl: genAvatar("photo-1494790108377-be9c29b29330"),
  },
};

const meta = {
  title: "Components/WorkMap/WorkMapTable",
  component: WorkMapTable,
  parameters: {
    layout: "padded",
  },
  tags: ["autodocs"],
  argTypes: {
    filter: {
      description: "Current filter applied to the WorkMapTable",
      options: [undefined, "all", "goals", "projects", "completed"],
      control: { type: "select" },
    },
    items: {
      description: "WorkMap items to display",
      control: "object",
    },
  },
} satisfies Meta<typeof WorkMapTable>;

export default meta;
type Story = StoryObj<typeof meta>;

const defaultGoalsAndProjects: WorkMap.Item[] = [
  {
    id: "goal-1",
    parentId: null,
    type: "goal",
    name: "Grow user base",
    status: "caution",
    progress: 40,
    space: { id: "space-growth", name: "Growth" },
    owner: people.igor,
    isNew: false,
    completedOn: null,
    closedAt: null,
    deadline: "Dec 31 2025",
    nextStep: "Launch referral program",
    timeframe: currentYear(),
    children: [
      {
        id: "project-1",
        parentId: "goal-1",
        type: "project",
        name: "Referral program",
        status: "on_track",
        progress: 60,
        space: { id: "space-growth", name: "Growth" },
        owner: people.jane,
        isNew: false,
        completedOn: null,
        deadline: "Nov 30 2025",
        closedAt: undefined,
        nextStep: "Design rewards",
        startedAt: "2025-01-15",
        children: [],
      },
      {
        id: "goal-1-1",
        parentId: "goal-1",
        type: "goal",
        name: "Increase signups by 20%",
        status: "completed",
        progress: 30,
        space: { id: "space-growth", name: "Growth" },
        owner: people.jane,
        isNew: false,
        completedOn: "2025-10-15",
        closedAt: null,
        deadline: "Oct 15 2025",
        nextStep: "A/B test new landing page",
        timeframe: currentYear(),
        children: [
          {
            id: "goal-100",
            parentId: "goal-1-1",
            type: "goal",
            name: "Finish Q2 OKRs",
            status: "missed",
            progress: 100,
            space: { id: "space-strategy", name: "Strategy" },
            owner: people.igor,
            isNew: false,
            completedOn: "2025-07-01",
            closedAt: "Jul 1 2025",
            nextStep: "",
            timeframe: currentQuarter(),
            children: [],
            deadline: null,
          },
          {
            id: "project-100",
            parentId: "goal-1-1",
            type: "project",
            name: "Migrate to Vite",
            status: "completed",
            progress: 100,
            space: { id: "space-eng", name: "Engineering" },
            owner: people.jennifer,
            isNew: false,
            completedOn: "2025-04-01",
            closedAt: "Apr 1 2025",
            nextStep: "",
            startedAt: "2025-01-01",
            children: [],
            deadline: null,
          },
        ],
      },
    ],
  },
  {
    id: "goal-2",
    parentId: null,
    type: "goal",
    name: "Improve onboarding",
    status: "paused",
    progress: 75,
    space: { id: "space-product", name: "Product" },
    owner: people.jennifer,
    isNew: false,
    completedOn: null,
    closedAt: null,
    deadline: "Aug 30 2025",
    nextStep: "Ship onboarding checklist",
    timeframe: currentYear(),
    children: [
      {
        id: "project-2",
        parentId: "goal-2",
        type: "project",
        name: "Onboarding checklist",
        status: "issue",
        progress: 80,
        space: { id: "space-product", name: "Product" },
        owner: people.jennifer,
        isNew: false,
        completedOn: null,
        closedAt: null,
        deadline: "Aug 15 2025",
        nextStep: "QA checklist",
        startedAt: "2025-03-15",
        children: [],
      },
    ],
  },
  {
    id: "project-3",
    parentId: null,
    type: "project",
    name: "Website redesign",
    status: "pending",
    progress: 50,
    space: { id: "space-design", name: "Design" },
    owner: people.igor,
    isNew: false,
    completedOn: null,
    closedAt: null,
    deadline: "Jul 31 2025",
    nextStep: "Finalize homepage",
    startedAt: "2025-02-01",
    children: [],
  },
];

const onlyGoals: WorkMap.Item[] = [
  {
    id: "goal-g1",
    parentId: null,
    type: "goal",
    name: "Increase NPS score",
    status: "caution",
    progress: 60,
    space: { id: "space-cs", name: "Customer Success" },
    owner: people.igor,
    isNew: false,
    completedOn: null,
    closedAt: null,
    deadline: "Sep 30 2025",
    nextStep: "Send Q3 survey",
    timeframe: currentQuarter(),
    children: [
      {
        id: "goal-g1-1",
        parentId: "goal-g1",
        type: "goal",
        name: "Launch new CSAT tool",
        status: "achieved",
        progress: 80,
        space: { id: "space-cs", name: "Customer Success" },
        owner: people.jane,
        isNew: false,
        completedOn: "2025-08-15",
        closedAt: null,
        deadline: "Aug 15 2025",
        nextStep: "Enable feedback widget",
        timeframe: currentMonth(),
        children: [],
      },
      {
        id: "goal-g1-2",
        parentId: "goal-g1",
        type: "goal",
        name: "Reduce churn by 10%",
        status: "missed",
        progress: 50,
        space: { id: "space-cs", name: "Customer Success" },
        owner: people.jennifer,
        isNew: false,
        completedOn: null,
        closedAt: null,
        deadline: "Sep 1 2025",
        nextStep: "Analyze churn data",
        timeframe: currentQuarter(),
        children: [],
      },
    ],
  },
  {
    id: "goal-g2",
    parentId: null,
    type: "goal",
    name: "Expand to APAC region",
    status: "partial",
    progress: 30,
    space: { id: "space-growth", name: "Growth" },
    owner: people.jane,
    isNew: false,
    completedOn: null,
    closedAt: null,
    deadline: "Dec 31 2025",
    nextStep: "Research local partners",
    timeframe: currentYear(),
    children: [
      {
        id: "goal-g2-1",
        parentId: "goal-g2",
        type: "goal",
        name: "Localize product",
        status: "pending",
        progress: 40,
        space: { id: "space-growth", name: "Growth" },
        timeframe: currentQuarter(),
        owner: people.igor,
        isNew: false,
        completedOn: null,
        closedAt: null,
        deadline: "Nov 15 2025",
        nextStep: "Hire translators",
        children: [],
      },
      {
        id: "goal-g2-2",
        parentId: "goal-g2",
        type: "goal",
        name: "APAC marketing campaign",
        status: "dropped",
        progress: 25,
        space: { id: "space-growth", name: "Growth" },
        owner: people.jennifer,
        isNew: false,
        completedOn: null,
        closedAt: null,
        deadline: "Dec 1 2025",
        nextStep: "Draft campaign assets",
        timeframe: currentQuarter(),
        children: [],
      },
    ],
  },
];

const onlyProjects: WorkMap.Item[] = [
  {
    id: "project-1",
    parentId: null,
    type: "project",
    name: "Mobile app v2",
    status: "dropped",
    progress: 70,
    startedAt: "2025-01-10",
    space: { id: "space-mobile", name: "Mobile" },
    owner: people.jane,
    isNew: false,
    completedOn: null,
    closedAt: null,
    deadline: "Sep 30 2025",
    nextStep: "Start beta testing",
    children: [],
  },
  {
    id: "project-2",
    parentId: null,
    type: "project",
    name: "API refactor",
    status: "paused",
    progress: 40,
    space: { id: "space-backend", name: "Backend" },
    owner: people.igor,
    isNew: false,
    completedOn: null,
    closedAt: null,
    deadline: "Oct 31 2025",
    nextStep: "Migrate endpoints",
    startedAt: "2025-02-15",
    children: [],
  },
  {
    id: "project-3",
    parentId: null,
    type: "project",
    name: "Website redesign",
    status: "achieved",
    progress: 50,
    space: { id: "space-design", name: "Design" },
    owner: people.jennifer,
    isNew: false,
    completedOn: "2025-07-31",
    closedAt: null,
    deadline: "Jul 31 2025",
    nextStep: "Finalize homepage",
    startedAt: "2025-03-01",
    children: [],
  },
];

const onlyCompleted: WorkMap.Item[] = [
  {
    id: "goal-10",
    parentId: null,
    type: "goal",
    name: "Achieve Series B funding",
    status: "completed",
    progress: 100,
    space: { id: "space-finance", name: "Finance" },
    owner: people.igor,
    isNew: false,
    completedOn: "2025-06-01",
    timeframe: currentYear(),
    deadline: "May 31 2025",
    closedAt: "Jun 1 2025",
    nextStep: "",
    children: [],
  },
  {
    id: "goal-11",
    parentId: null,
    type: "goal",
    name: "Hit 100k MAU",
    status: "completed",
    progress: 100,
    space: { id: "space-growth", name: "Growth" },
    isNew: false,
    completedOn: "2025-05-15",
    closedAt: "May 1 2025",
    owner: people.jane,
    deadline: "Apr 30 2025",
    nextStep: "",
    timeframe: currentQuarter(),
    children: [],
  },
  {
    id: "project-10",
    parentId: null,
    type: "project",
    name: "Migrate to Vite",
    status: "completed",
    progress: 100,
    space: { id: "space-eng", name: "Engineering" },
    owner: people.jennifer,
    isNew: false,
    completedOn: "2025-04-01",
    closedAt: "Apr 1 2025",
    nextStep: "",
    startedAt: "2025-01-15",
    children: [],
    deadline: null,
  },
];

export const Default: Story = {
  args: {
    items: defaultGoalsAndProjects,
    filter: "all",
    deleteItem: (itemId: WorkMap.Item["id"]) => console.log("Delete", itemId),
    addItem: (newItem) => console.log("Add", newItem),
  },
};

export const GoalsOnly: Story = {
  args: {
    items: onlyGoals,
    filter: "goals",
    deleteItem: (itemId: WorkMap.Item["id"]) => console.log("Delete", itemId),
    addItem: (newItem) => console.log("Add", newItem),
  },
};

export const ProjectsOnly: Story = {
  args: {
    items: onlyProjects,
    filter: "projects",
    deleteItem: (itemId: WorkMap.Item["id"]) => console.log("Delete", itemId),
    addItem: (newItem) => console.log("Add", newItem),
  },
};

export const CompletedOnly: Story = {
  args: {
    items: onlyCompleted,
    filter: "completed",
    deleteItem: (itemId: WorkMap.Item["id"]) => console.log("Delete", itemId),
    addItem: (newItem) => console.log("Add", newItem),
  },
};
