//
// Automatically generated with mix operate.gen.feed.items.index
// Do not edit this file manually
//

import { FeedItem } from "../FeedItem";

import { CommentAdded } from "./CommentAdded"
import { DiscussionCommentSubmitted } from "./DiscussionCommentSubmitted"
import { DiscussionEditing } from "./DiscussionEditing"
import { DiscussionPosting } from "./DiscussionPosting"
import { GoalArchived } from "./GoalArchived"
import { GoalCheckIn } from "./GoalCheckIn"
import { GoalCheckInAcknowledgement } from "./GoalCheckInAcknowledgement"
import { GoalCheckInEdit } from "./GoalCheckInEdit"
import { GoalClosing } from "./GoalClosing"
import { GoalCreated } from "./GoalCreated"
import { GoalEditing } from "./GoalEditing"
import { GoalReparent } from "./GoalReparent"
import { GoalTimeframeEditing } from "./GoalTimeframeEditing"
import { ProjectArchived } from "./ProjectArchived"
import { ProjectCheckInAcknowledged } from "./ProjectCheckInAcknowledged"
import { ProjectCheckInCommented } from "./ProjectCheckInCommented"
import { ProjectCheckInEdit } from "./ProjectCheckInEdit"
import { ProjectCheckInSubmitted } from "./ProjectCheckInSubmitted"
import { ProjectClosed } from "./ProjectClosed"
import { ProjectContributorAddition } from "./ProjectContributorAddition"
import { ProjectCreated } from "./ProjectCreated"
import { ProjectGoalConnection } from "./ProjectGoalConnection"
import { ProjectGoalDisconnection } from "./ProjectGoalDisconnection"
import { ProjectMilestoneCommented } from "./ProjectMilestoneCommented"
import { ProjectMoved } from "./ProjectMoved"
import { ProjectPausing } from "./ProjectPausing"
import { ProjectRenamed } from "./ProjectRenamed"
import { ProjectResuming } from "./ProjectResuming"
import { ProjectTimelineEdited } from "./ProjectTimelineEdited"
import { SpaceJoining } from "./SpaceJoining"
import { TaskAdding } from "./TaskAdding"
import { TaskDescriptionChange } from "./TaskDescriptionChange"
import { TaskStatusChange } from "./TaskStatusChange"
import { TaskUpdate } from "./TaskUpdate"

const FeedItems : FeedItem[] = [
  CommentAdded,
  DiscussionCommentSubmitted,
  DiscussionEditing,
  DiscussionPosting,
  GoalArchived,
  GoalCheckIn,
  GoalCheckInAcknowledgement,
  GoalCheckInEdit,
  GoalClosing,
  GoalCreated,
  GoalEditing,
  GoalReparent,
  GoalTimeframeEditing,
  ProjectArchived,
  ProjectCheckInAcknowledged,
  ProjectCheckInCommented,
  ProjectCheckInEdit,
  ProjectCheckInSubmitted,
  ProjectClosed,
  ProjectContributorAddition,
  ProjectCreated,
  ProjectGoalConnection,
  ProjectGoalDisconnection,
  ProjectMilestoneCommented,
  ProjectMoved,
  ProjectPausing,
  ProjectRenamed,
  ProjectResuming,
  ProjectTimelineEdited,
  SpaceJoining,
  TaskAdding,
  TaskDescriptionChange,
  TaskStatusChange,
  TaskUpdate
];

export default FeedItems;
