//
// Automatically generated with mix operate.gen.feed.items.index
// Do not edit this file manually
//

import { FeedItem } from "../FeedItem";

import { ProjectCreated } from "./ProjectCreated";
import { ProjectCheckInSubmitted } from "./ProjectCheckInSubmitted";
import { ProjectCheckInAcknowledged } from "./ProjectCheckInAcknowledged";
import { ProjectArchived } from "./ProjectArchived";
import { ProjectMoved } from "./ProjectMoved";
import { ProjectContributorAddition } from "./ProjectContributorAddition";
import { ProjectRenamed } from "./ProjectRenamed";

const FeedItems: FeedItem[] = [
  ProjectCreated,
  ProjectCheckInSubmitted,
  ProjectCheckInAcknowledged,
  ProjectArchived,
  ProjectMoved,
  ProjectContributorAddition,
  ProjectRenamed,
];

export default FeedItems;
