#!/bin/bash

count() {
  gh issue list --repo operately/operately --limit 100 --search "is:open label:$1" --json title --template '{{range .}}{{.title}}{{"\n"}}{{end}}' | wc -l
}

echo "Bugs:             $(count bug)"
echo "Papercut:         $(count papercut)"
echo "Enhancements:     $(count enhancement)"
echo "Feature Requests: $(count feature-request)"
echo "Spec needed:      $(count spec-needed)"
echo "Dev Productivity: $(count dev-productivity)"
