defmodule Mix.Tasks.Operately.Gen.Turboui.ApiTypesTest do
  use ExUnit.Case

  import ExUnit.CaptureIO

  test "generates TurboUI API types in the requested file" do
    out_dir = Path.join(System.tmp_dir!(), "operately_mix_turboui_api_types_#{System.unique_integer([:positive])}")
    out_file = Path.join(out_dir, "index.ts")

    on_exit(fn ->
      File.rm_rf(out_dir)
    end)

    Mix.Task.reenable("operately.gen.turboui.api_types")

    output =
      capture_io(fn ->
        Mix.Task.run("operately.gen.turboui.api_types", ["--out-file", out_file])
      end)

    assert output =~ "Generating"
    assert output =~ out_file
    assert File.exists?(out_file)

    content = File.read!(out_file)

    assert content =~ "Automatically generated by mix operately.gen.turboui.api_types"
    assert content =~ "export type Id = string;"
    assert content =~ "export interface ResourceHubNode"

    refute content =~ "import React"
    refute content =~ "import axios"
    refute content =~ "useQuery"
    refute content =~ "useMutation"
    refute content =~ "ApiClient"
    refute content =~ "export async function"
    refute content =~ "GetThemeInput"
    refute content =~ "GetThemeResult"
  end

  test "raises for unknown options" do
    Mix.Task.reenable("operately.gen.turboui.api_types")

    assert_raise Mix.Error, ~r/Unknown option\(s\): --unknown/, fn ->
      Mix.Task.run("operately.gen.turboui.api_types", ["--unknown", "value"])
    end
  end
end
