//
// Automatically generated with mix operate.gen.notification.items.index
// Do not edit this file manually
//

import * as React from "react";

import ProjectArchived from "./ProjectArchived"
import ProjectCreated from "./ProjectCreated"
import ProjectDiscussionCommentSubmitted from "./ProjectDiscussionCommentSubmitted"
import ProjectDiscussionSubmitted from "./ProjectDiscussionSubmitted"
import ProjectRenamed from "./ProjectRenamed"
import ProjectReviewAcknowledged from "./ProjectReviewAcknowledged"
import ProjectReviewRequestSubmitted from "./ProjectReviewRequestSubmitted"
import ProjectReviewSubmitted from "./ProjectReviewSubmitted"
import ProjectStatusUpdateAcknowledged from "./ProjectStatusUpdateAcknowledged"
import ProjectStatusUpdateCommented from "./ProjectStatusUpdateCommented"
import ProjectStatusUpdateSubmitted from "./ProjectStatusUpdateSubmitted"

export default function NotificationItem({notification}) {
  const activityType = notification.activity.content.__typename;

  switch (activityType) {
    case "ActivityContentProjectArchived":
      return <ProjectArchived notification={notification} />;
    
    case "ActivityContentProjectCreated":
      return <ProjectCreated notification={notification} />;
    
    case "ActivityContentProjectDiscussionCommentSubmitted":
      return <ProjectDiscussionCommentSubmitted notification={notification} />;
    
    case "ActivityContentProjectDiscussionSubmitted":
      return <ProjectDiscussionSubmitted notification={notification} />;
    
    case "ActivityContentProjectRenamed":
      return <ProjectRenamed notification={notification} />;
    
    case "ActivityContentProjectReviewAcknowledged":
      return <ProjectReviewAcknowledged notification={notification} />;
    
    case "ActivityContentProjectReviewRequestSubmitted":
      return <ProjectReviewRequestSubmitted notification={notification} />;
    
    case "ActivityContentProjectReviewSubmitted":
      return <ProjectReviewSubmitted notification={notification} />;
    
    case "ActivityContentProjectStatusUpdateAcknowledged":
      return <ProjectStatusUpdateAcknowledged notification={notification} />;
    
    case "ActivityContentProjectStatusUpdateCommented":
      return <ProjectStatusUpdateCommented notification={notification} />;
    
    case "ActivityContentProjectStatusUpdateSubmitted":
      return <ProjectStatusUpdateSubmitted notification={notification} />;
    
    default:
      throw "unhandled activity type " + activityType + " in assets/js/pages/NotificationsPage/NotificationItem/index.tsx";
  }
}
