import React from "react";
import classNames from "../utils/classnames";
import { Modal } from "../Modal";
import { PrimaryButton, SecondaryButton } from "../Button";
import { IconPlus, IconTrash } from "../icons";
import { StatusSelector } from "../StatusSelector";
import { useSortableList, useSortableItem, DropIndicator, DragHandle } from "../utils/PragmaticDragAndDrop";
import {
  StatusAppearance,
  StatusAppearancePicker,
  STATUS_APPEARANCES,
  APPEARANCE_ORDER,
} from "./StatusAppearancePicker";

export interface StatusCustomizationModalProps {
  isOpen: boolean;
  onClose: () => void;
  statuses: ReadonlyArray<StatusSelector.StatusOption>;
  onSave: (nextStatuses: StatusSelector.StatusOption[]) => void;
  title?: string;
}

const useDraftStatuses = (source: ReadonlyArray<StatusSelector.StatusOption>, isOpen: boolean) => {
  const createDraft = React.useCallback(
    () => (source.length > 0 ? source : [buildStatus(undefined, 0)]).map((status, index) => buildStatus(status, index)),
    [source],
  );

  const [drafts, setDrafts] = React.useState<StatusSelector.StatusOption[]>(createDraft);

  React.useEffect(() => {
    if (isOpen) {
      setDrafts(createDraft());
    }
  }, [createDraft, isOpen]);

  return [drafts, setDrafts] as const;
};

export function StatusCustomizationModal({
  isOpen,
  onClose,
  statuses,
  onSave,
  title = "Customize statuses",
}: StatusCustomizationModalProps) {
  const [draftStatuses, setDraftStatuses] = useDraftStatuses(statuses, isOpen);
  const { sanitizedStatuses, showValidation, handleSave } = useStatusSaving(draftStatuses, onSave, isOpen);

  const updateStatus = (id: string, updates: Partial<StatusSelector.StatusOption>) => {
    setDraftStatuses((prev) =>
      prev.map((status) => {
        if (status.id !== id) return status;

        const updatedStatus = { ...status, ...updates };

        // Auto-generate value from label
        if (updates.label !== undefined) {
          const previousLabelSlug = generateStatusValueFromLabel(status.label ?? "");
          const isAutoGenerated = !status.value || status.value === previousLabelSlug;

          if (isAutoGenerated) {
            updatedStatus.value = generateStatusValueFromLabel(updates.label);
          }
        }

        // Update hidden property when color/icon changes (appearance change)
        if (updates.color !== undefined || updates.icon !== undefined) {
          const newAppearance = getAppearanceFromStatus(updatedStatus);
          updatedStatus.closed = newAppearance === "green" || newAppearance === "red";
        }

        return updatedStatus;
      }),
    );
  };

  const removeStatus = (id: string) => {
    setDraftStatuses((prev) => (prev.length <= 1 ? prev : prev.filter((status) => status.id !== id)));
  };

  const addStatus = () => {
    setDraftStatuses((prev) => [...prev, buildStatus(undefined, prev.length)]);
  };

  const handleReorder = (itemId: string, newIndex: number) => {
    setDraftStatuses((prev) => {
      const oldIndex = prev.findIndex((s) => s.id === itemId);
      if (oldIndex === -1) return prev;

      const reordered = [...prev];
      const [moved] = reordered.splice(oldIndex, 1);
      if (!moved) return prev;

      reordered.splice(newIndex, 0, moved);

      return reordered.map((status, index) => ({ ...status, index }));
    });
  };

  useSortableList(draftStatuses, handleReorder);

  return (
    <Modal isOpen={isOpen} onClose={onClose} title={title} size="large" contentPadding="p-0">
      <div className="p-6 space-y-4">
        <p className="text-sm text-content-dimmed">Add, edit, or remove task statuses. Click the icon to change the color and appearance.</p>

        <div className="space-y-3">
          {draftStatuses.map((status, index) => {
            const isLabelInvalid = showValidation && sanitizedStatuses[index]?.label.length === 0;
            return (
              <StatusRow
                key={status.id}
                status={status}
                isLabelInvalid={isLabelInvalid}
                onUpdate={updateStatus}
                onRemove={removeStatus}
                canRemove={draftStatuses.length > 1}
              />
            );
          })}
        </div>

        <button
          type="button"
          onClick={addStatus}
          className="w-full rounded-lg border border-dashed border-surface-outline py-2 text-sm font-medium text-content-dimmed transition hover:text-brand-1 hover:border-brand-1/50 flex items-center justify-center gap-2"
        >
          <IconPlus size={14} />
          Add status
        </button>
      </div>

      <div className="flex flex-col gap-4 px-6 py-4 border-t border-surface-outline">
        <div className="flex flex-col sm:flex-row gap-3 sm:justify-end">
          <SecondaryButton type="button" onClick={onClose}>
            Cancel
          </SecondaryButton>
          <PrimaryButton type="button" onClick={handleSave}>
            Save changes
          </PrimaryButton>
        </div>
      </div>
    </Modal>
  );
}

type StatusRowProps = {
  status: StatusSelector.StatusOption;
  isLabelInvalid: boolean;
  onUpdate: (id: string, updates: Partial<StatusSelector.StatusOption>) => void;
  onRemove: (id: string) => void;
  canRemove: boolean;
};

function StatusRow({ status, isLabelInvalid, onUpdate, onRemove, canRemove }: StatusRowProps) {
  const { ref, dragHandleRef, isDragging, closestEdge } = useSortableItem({
    itemId: status.id,
    index: status.index,
  });

  return (
    <div className="relative">
      {closestEdge === "top" && <DropIndicator edge="top" />}
      <div
        ref={ref as React.RefObject<HTMLDivElement>}
        className={classNames("flex items-center gap-2 group", isDragging && "opacity-50")}
      >
        <div ref={dragHandleRef as React.RefObject<HTMLDivElement>} className="flex items-center">
          <DragHandle isDragging={isDragging} className="opacity-100" />
        </div>
        <StatusAppearancePicker
          value={getAppearanceFromStatus(status)}
          onChange={(appearance) => {
            const preset = STATUS_APPEARANCES[appearance];
            onUpdate(status.id, { color: preset.color, icon: preset.icon });
          }}
        />
        <input
          value={status.label}
          onChange={(event) => onUpdate(status.id, { label: event.target.value })}
          placeholder="Status label"
          className={classNames(
            "flex-1 rounded-md border px-3 py-2 text-sm text-content-base transition focus:outline-none focus:ring-2 focus:ring-brand-1",
            isLabelInvalid ? "border-rose-300 focus:ring-rose-400" : "border-stroke-base",
          )}
        />
        <button
          type="button"
          onClick={() => onRemove(status.id)}
          className={classNames(
            "p-1 rounded transition",
            !canRemove
              ? "text-content-subtle cursor-not-allowed opacity-50"
              : "text-content-dimmed hover:text-red-500 hover:bg-red-50",
          )}
          aria-label="Remove status"
          disabled={!canRemove}
        >
          <IconTrash size={16} />
        </button>
      </div>
      {closestEdge === "bottom" && <DropIndicator edge="bottom" />}
    </div>
  );
}

const useStatusSaving = (
  draftStatuses: ReadonlyArray<StatusSelector.StatusOption>,
  onSave: (nextStatuses: StatusSelector.StatusOption[]) => void,
  isOpen: boolean,
) => {
  const [showValidation, setShowValidation] = React.useState(false);

  React.useEffect(() => {
    if (isOpen) {
      setShowValidation(false);
    }
  }, [isOpen]);

  const sanitizedStatuses = React.useMemo(
    () => draftStatuses.map((status) => ({ ...status, label: status.label.trim() })),
    [draftStatuses],
  );

  const hasEmptyLabel = sanitizedStatuses.some((status) => status.label.length === 0);

  const handleSave = () => {
    if (hasEmptyLabel) {
      setShowValidation(true);
      return;
    }
    onSave(sanitizedStatuses);
  };

  return { sanitizedStatuses, showValidation, handleSave };
};

/**
 * Generates a status value from a label by converting to lowercase and replacing spaces with underscores.
 * @returns The generated value (e.g., "In Progress" -> "in_progress")
 */
function generateStatusValueFromLabel(label: string): string {
  return label.toLowerCase().replace(/\s+/g, "_");
}

const generateId = () =>
  typeof crypto !== "undefined" && "randomUUID" in crypto
    ? crypto.randomUUID()
    : `status-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`;

const getAppearanceFromStatus = (status?: Partial<StatusSelector.StatusOption>): StatusAppearance => {
  if (!status) return "gray";
  const found = APPEARANCE_ORDER.find((appearance) => {
    const preset = STATUS_APPEARANCES[appearance];
    return status.color === preset.color && status.icon === preset.icon;
  });
  return found ?? "gray";
};

const buildStatus = (
  status?: Partial<StatusSelector.StatusOption>,
  index?: number,
): StatusSelector.StatusOption => {
  const appearance = getAppearanceFromStatus(status);
  const preset = STATUS_APPEARANCES[appearance];

  return {
    id: status?.id ?? generateId(),
    value: status?.value ?? "",
    label: status?.label ?? "",
    color: preset.color,
    icon: preset.icon,
    index: status?.index ?? index ?? 0,
    closed: status?.closed ?? (appearance === "green" || appearance === "red"),
  };
};
